### ISSUE TITLE
Client Source Request?

### ISSUE THREAD

**Issue by Juestrix** [JaraLowell/OgarServ#10]
Hello I love what you have done with this fork of Ogar. I am interested in a client like the one one your website. I don't need any styling I would just like a barebones full functioning version. Including a source required for the match results page. I can compensate you with $$$. Please lmk!

**Comment by JaraLowell** [comment]
The server, writes the scores to MySQL, (if configured to do so) so you only need make a small bit of PHP code to read it and put it on a page.

**Comment by Juestrix** [comment]
Jara,

I have a client fully functioning except "Match Results"  does not appear when you die... see screenshot of your site.

![screen shot 2015-11-02 at 9 42 13 pm](https://cloud.githubusercontent.com/assets/15260073/10903143/ace600f4-81aa-11e5-985d-cd6b6a03f030.png)

What I need is how to make that screen appear.

Thanks!

**Comment by JaraLowell** [comment]
My 'client' is just an example of what you all can do with a little of java script editing and css changing. You would only need to look in the the page source to see how, where and when it be done if you follow the script. If you do not understand java then it would be rather  hard to explain. Be like explaining an language to you that is totally not custom to you. There be no guides, or you tube movies on how to make or duplicate small parts of that. Put some time in to reading the code, learn it a little and it so, after some time makes sense and you soon after can make, your own changes. But do not go to peoples sites and expect to like instantly have and get what you see, if you do not understand how it was all done.

My site is there to learn, the server is here to help. All you now have to do, is combine, and.. if possible; give a little credit towards the weeks of work, i did put in to it all.

**Comment by Juestrix** [comment]
Please re-read my first post, I started it with a compliment to you, and I also stated I would compensate you for your time. I'm not asking for freebies.... I also stated I did not want your styling or to copy it. A barebones fully functioning client... is what I'm seeking help with!

I have every intention of creating something completely unique. 

Your final reply was rather condescending and less helpful. 

Goodbye.
