### ISSUE TITLE
Food disappears when you are 5000+ Mass.

### ISSUE THREAD

**Issue by ortex112** [JaraLowell/OgarServ#101]
Food disappears when i'm 5000+ Mass please tell me how to fix it.

**Comment by JaraLowell** [comment]
That is done purposely to lower bandwidth to make sure you wont lag out the client with to many 'objects', this is currently the main issue we see. It not per say the server that lags out right now, but the combination of things and one thing the client no like, is to many bubbles. So as a test we disable seeing food once your own size is over 5k. It can be tweaked however in playertracker.js

**Comment by ortex112** [comment]
You said (Skin support update), how i can use skins?

**Comment by JaraLowell** [comment]
Skin support is an package send and received by the server. It noting special really other then when receiving a user name that starts with <premium skin name>  the server sends back a %skinname to the client. The client can then use this to select an image. As per agar.io's ways.

**Comment by ortex112** [comment]
and please make popping virus more smooth because i want to make popsplits and vanish splits with bots
Thanks.
