### ISSUE TITLE
Where does Skin files go?

### ISSUE THREAD

**Issue by taeukkang** [JaraLowell/OgarServ#103]
Hi Jara,

Any way to insert skin files on OgarServ?
Is that on the client side?

Thanks.

**Comment by Andrews54757** [comment]
No, there is no skins file for ogarserv. But ogar unlimited has it

**Comment by JaraLowell** [comment]
Skin files go there where your client gets them from, same for ogar unlimited; they do not own a skin nor actually have rights to add some that are adding as is.

**Comment by ortex112** [comment]
Then how to use skins please tell me easily to understand.
Thanks.

**Comment by Andrews54757** [comment]
in ogar unlimited, you can create custom skins by editing the customskins.txt file
