### ISSUE TITLE
Problem with bots

### ISSUE THREAD

**Issue by NicholasNDB** [JaraLowell/OgarServ#106]
The bots are not intelligent or good at all, for example, almost all bots are split as many times as they can making it easy to get them. If i am bigger than a bot, even just a little, it will split to 16 making any strategy useless because they make themselves so vulnerable. They also like to run into viruses then split even more. The bot in the picture was bigger than me but started splitting, and i ate him a little bit while trying to capture the screen shot. Is there a way to fix this 
![untitled](https://cloud.githubusercontent.com/assets/17709089/13579120/4d16b46a-e461-11e5-8c4b-2cea4d51d1f7.png)

**Comment by JaraLowell** [comment]
Bot where never intended to be like super smart,. nor can they really be within the server. As in end there a limit of resources you want to give them, before they hog up all the tick time of the server to make an decision. There are some bots out there that leurn and what not, but they not per say, ready for a server side implementation, nor are even they, that smart.

**Comment by NicholasNDB** [comment]
I thought it was a bit weird because some other private servers i had tried had bots that would only split             once, into two pieces, so, they wouldnt be in lots of pieces. is there a way i can limit the bots splits to once so they are only in 2 pieces but still be popped by virus to the max of 16 pieces

**Comment by JaraLowell** [comment]
True that be possible to, but as we have a nice math, that punishes when eating really small cels; it why we decided to allow the bots to max split so people no seem them as mere food! :imp:

**Comment by Andrews54757** [comment]
im gonna try to add that to my version

**Comment by JaraLowell** [comment]
Am testing a wee bit on randomizing to the bots spiting so it not always maxed or not even always happening

**Comment by Andrews54757** [comment]
i added it

**Comment by JaraLowell** [comment]
Best way however would be if a small group perhaps could see if Apostolique bot might be able to fork a version that would work with Ogar. It not gone be easy that is for sure but would give a better bot.

**Comment by Andrews54757** [comment]
no, not really as his has a limited functionality, good formula, but not so good
