### ISSUE TITLE
Mysql connection problem

### ISSUE THREAD

**Issue by Ciao121** [JaraLowell/OgarServ#107]
Hi,
I have a mysql connection problem.
When I start the server I get

```
MySQL config loaded Database set to NaN.NaN
MySQL Error!
Error: connect ECONNREFUSED
```

errors in console.
Logging "this.mysql.createConnection" i see strange thing like:

> config: 
>    { host: 192.168,  **<-this should be, as in my mysql.ini,192.168.0.10
>      password: undefined,
>      database: NaN,

As ever i'm trying to implement your mods in my own modded ogar, not using your source files. Any hint for me?

Thank you.

**Comment by Ciao121** [comment]
Sorry,
problem was due a wrog format in mysql.ini (newline problems).

**Comment by JaraLowell** [comment]
That is what you get when using others peoples work without checking the whole commit that goes with it :smiling_imp: check `ini.js` as that is why it goes wrong. The original does not let you read none numbers as return value.

**Comment by Ciao121** [comment]
Yeah! It's working.
You are absolutely right when you say I didn't check the whole commit. Problem is I started using Git (not as developer) something like 5 months ago. I'm not really inside how it works. I'm just trying to understand updates looking for differences between my modded files and files I get from git. And trying to understand which mods concerns the feature I'd like to "import" in my version, excluding all others mods.

I have to better understand the commits system so it should be easier for me to get exactly what I need.

Thank you again!!!
