### ISSUE TITLE
hscore value

### ISSUE THREAD

**Issue by Ciao121** [JaraLowell/OgarServ#108]
Hi,
I noticed that hscore value, used in highscores, is alway minor than the Score value displayed while playing or the highest mass value in the stats windows. The bigger the reached mass the bigger the difference.

I think this is because hscore is calculated in PlayerTracker something like once per second and it always lower than the max reached score because of mass decay.

Any suggestion to have hscore updated in realtime? In example when (and if) the max score is sent to the client to be displayed. If this is not an option (maybe max score is only client sided.. don't know)... any other idea?

Thank you!

**Comment by JaraLowell** [comment]
You can try, calling getScore(1);  more often, though remember so to, calling certain functions more, can and will cause lag in the server. 

Score is not send to the client, the client calculates it as well. There can even be a difference if the calculation of the score in server is different then the math used in the client.
