### ISSUE TITLE
Much lag

### ISSUE THREAD

**Issue by joery1337** [JaraLowell/OgarServ#109]
Hello,

When there are around 20 people, there is much lag.

CPU usage is only 13%, and memory usage is 15%.

I've used OVH and Vultr.com servers, and there is much lag at both of them.

What could it be?

**Comment by makandz** [comment]
No it is the server files themself, I can confirm this. Try using an older version of OgarServ. Honestly, I use version 1.5.9 on my server and it is the _most_ stable.

https://github.com/JaraLowell/OgarServ/releases/tag/1.5.9

**Comment by joery1337** [comment]
@MastaCoder thanks, I'm trying to figure out what's causing the lag at the moment.

**Comment by makandz** [comment]
I think it's the collision of splits or w's in general. Not sure yet.

**Comment by JaraLowell** [comment]
Personally think it physics of 'Cell' that causes it,. there two loops in there one to move, and one to test for collisions,. so with many people; them loops can cause an issue while we in the older version not had that. That is least one huge change we have 164 vs 159, as there seems no other area really that causes huge or large lag issues that i can pin point.

**Comment by joery1337** [comment]
@JaraLowell using the older physics it decreased lag. Sometimes the movement of cells stutters, could it be possible that the UpdateNodes packet is sent too late sometimes?

**Comment by JaraLowell** [comment]
Only real lag i see lately is people from the other side of the world playing on my server. (Example Mexico, japan and country's like that) as locally when i watch, i do not see a whole lot of lag. Mean remember, the game server sends out like every 500ms a package to the client, so if your ping to server is more then 1s (aka ping is 1000 or more)  you receive it to late and send it to late and that cycles upwards in a spiral of a LOT of lag for you as player. Perhaps a kick on lo latency be an option, like if your latency is more then 500, buh bye~ lol mean might sound harsh, but that is what done in vavle's game, Half Life  and Quake 3 Arena. Fast FPS games, need a good ping, if you as player not have that (wife and a really bad tabled)  you wont play this game smoothly.
