### ISSUE TITLE
How Do I use skins please tell me.

### ISSUE THREAD

**Issue by ortex112** [JaraLowell/OgarServ#110]
I don't know how to use skins please can you tell me how?

**Comment by Andrews54757** [comment]
Do you mean custom skins? To use it, shorten the skin img url and encase it between | and |. Enter that into the nickname box. I suggest if you want to have your own skin shortcuts, i.e. Instead of the url, you type in <dark spy> instead of a url, you use Ogar unlimited

**Comment by ortex112** [comment]
i dont understand...
can you make it more understandable please

**Comment by Andrews54757** [comment]
So for in game skins by agar.io, you have to do <skinname> your name in the nickname box in the client. For other outside skins. You need to use || instead of <> . but it is complicated so I recommend Ogar unlimited if you want custom, non in game skins

**Comment by ortex112** [comment]
OH OK Thanks
