### ISSUE TITLE
5000 point problem

### ISSUE THREAD

**Issue by unblockedgamess** [JaraLowell/OgarServ#111]
Baits just past 5000 points in the new version are missing.

**Comment by makandz** [comment]
I think it does that on purpose.

**Comment by unblockedgamess** [comment]
I could not figure I do not know.
 some users are experiencing a problem lagoon
 I'll make her investigation is going on very busy servers.

**Comment by JaraLowell** [comment]
Already bin addressed, is done on purpose to lower bandwidth lag or more to test if that helps players once they pass 5K in mass.
