### ISSUE TITLE
I cant open the server

### ISSUE THREAD

**Issue by ortex112** [JaraLowell/OgarServ#112]
When I try to open the server i make start.bat 
it gives me this
\ |-------------------------------------------------------------------------------------------------------------------|
and then this
loadDep:readable-stream - \ |#######################------------------------------------------------------------------|
and closes.

**Comment by JaraLowell** [comment]
That is actualy npm (node package manager) failing to install the needed packages.

**Comment by ortex112** [comment]
yes

**Comment by ortex112** [comment]
how do i fix this

**Comment by ortex112** [comment]
but it extracts some files and closes

**Comment by JaraLowell** [comment]
you can always try in cmd screen, to go to the folder where the bat file is, and do the npm step manual see if you then get an error or least see one.

**Comment by ortex112** [comment]
i dont know what is the steps
