### ISSUE TITLE
jxcore error

### ISSUE THREAD

**Issue by skysea** [JaraLowell/OgarServ#113]
http://jxcore.com/xil.sh  not found page

**Comment by JaraLowell** [comment]
Yes we seen this, apparently JXCore moved and changed there linux install bash file _mutters_ for now i would suggest to visit JXCore's website and manually install JXCore

**Comment by JaraLowell** [comment]
changed to curl https://raw.githubusercontent.com/jxcore/jxcore/master/tools/jx_install.sh | bash
