### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by unblockedgamess** [JaraLowell/OgarServ#116]
Hello, I downloaded version 1.64.
but I noticed that made many updates to the issues section
Do we have a chance to download a version that these updates?

**Comment by JaraLowell** [comment]
Am fine tuning a few things in current revision, when i am happy with the fine tuning i will create 1.6.5 release for you all to get, i hope that will be his weekend :smile_cat:

**Comment by makandz** [comment]
Or you can hit the download zip button to get them all now xD
