### ISSUE TITLE
big bot balls , server client crash

### ISSUE THREAD

**Issue by efsysefsys** [JaraLowell/OgarServ#117]
Hello! tnx for very nice files! All work ! But have problem when i add bots play 20 sec , starting big lags and my ball stoped. and around very big balls see only colours green blue etc.I set gameversion 0.Sorry for my bad eng. I make some screenshots

some screens here:

http://www.bildites.lv/images/5ibpul3uaeicuqkf9zm.png

http://www.bildites.lv/images/7ond12szv2swd5lcro4b.png

http://www.bildites.lv/images/9c4ef0t10hxm1k4b7v37.png

p.s. where i can delete [BOT] prefix? :)

**Comment by Botanistt** [comment]
"paškodēts" skaidrs ar jums.

**Comment by JaraLowell** [comment]
That is more an Client issue then a server. Mean the big ball issue, bot names one can change in ai/BotLoader.js
