### ISSUE TITLE
Running server

### ISSUE THREAD

**Issue by Botanistt** [JaraLowell/OgarServ#118]
Hello.
Want to run this script a lot, read that it has 'auto' install feature for packages which doesn't exist but it doesn't.
I isntalled JXcore manually and when trying to run runnode.sh it outputs this:
./runnode.sh: line 11: node: command not found
Server went off, waiting ten sec then restarting it...
According to line number 11 it's node but I installed node (apt-get install nodejs). What am I missing or doing wrong? Thanks in advance!
;)

**Comment by Botanistt** [comment]
Seems like it's working somehow but when I'm trying to access it all I see is "Upgrade Required".
I downloaded latest version from github and also tried changing protocol, same message.
Any advice?

**Comment by JaraLowell** [comment]
node needs NPM,. and i guess that is why it not working you installed nodejs but possibly not the node package manager.

**Comment by skysea** [comment]
nodejs Which version of need

**Comment by JaraLowell** [comment]
@skysea see https://github.com/JaraLowell/OgarServ/issues/114

**Comment by skysea** [comment]
@JaraLowell  thank you
