### ISSUE TITLE
Server run problem

### ISSUE THREAD

**Issue by skysea** [JaraLowell/OgarServ#119]
![sss](https://cloud.githubusercontent.com/assets/1094526/13901532/defdc800-ee2f-11e5-9cb5-27de91bb56e7.png)

Please help me :)

**Comment by makandz** [comment]
@JaraLowell I told you this bug is on the latest version xD

@skysea To fix this temporarily, open gameserver.ini and change the loglevel to 0.

**Comment by skysea** [comment]
:) thank you

**Comment by JaraLowell** [comment]
i wonder how that even possible.. or you grabbed a version in between as when you log in the GIT source, you will not find gameServ..... but what it should be :smiling_imp:

**Comment by Botanistt** [comment]
I'm having same issue.

**Comment by JaraLowell** [comment]
Okay.... my bad, fixed in Commit 320
