### ISSUE TITLE
Option to stop console.log for messages.

### ISSUE THREAD

**Issue by makandz** [JaraLowell/OgarServ#12]
I would add a settings in the gameserver.ini that let's a user choose to see the messages of the chat in the console.log or not. I checked the PacketHandler.js file and found the console.log that ran it. Maybe add a variable that if true will show the chat log in the console.

I am only saying this for the people running a server for x days. The console get's extremely filled up and fast. Maybe also add an option for the "Client tried to connect but server is full" log too.

I had to disable both of these through the actual JS files, but it would be nice if you could disable it in the gameserver.ini options.

**Comment by JaraLowell** [comment]
Good idea, i can see that chat clutters the logs,. And as it logged to a separated file as well it easy could be disabled to console.

**Comment by mdluffy01** [comment]
please how login on chat admin

**Comment by makandz** [comment]
/rcon in the chat. Also please don't ask questions on other issues :)

**Comment by mdluffy01** [comment]
thnk i am new

**Comment by JaraLowell** [comment]
This option now active in git version, when ban list saving as finished it be in the release.
