### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by Botanistt** [JaraLowell/OgarServ#122]
Hello!
I installed this and I'm grateful for this but I wanted to know how to create server that looks like in your screenshot. Took a while for me to figure out how to connect to the server and seems like I have to go through agar.io but I want it to be like mydomain.com. Also I can't access chat. 
Please help me on this, I'm really confused here.

**Comment by Botanistt** [comment]
Anyone?

**Comment by JaraLowell** [comment]
There are like 12 Issues closed for this,. so no you wont get any answer if you do not take the time t browse previous placed same questions.

So again, we here only and only make the server. You can use the server using agar.io. We do not hand out clients or aid with custom private clients. For that there be a number of forums out there.

**Comment by Andrews54757** [comment]
well, i searched up the forum _you_ gave me but i couldnt find it so i dont think anyone else can find one easily either

**Comment by JaraLowell** [comment]
http://forum.ragezone.com/f925/

**Comment by Andrews54757** [comment]
still cant find any

**Comment by JaraLowell** [comment]
lol seriously... 2 clicks.. http://forum.ragezone.com/f927/release-agariopvp-custom-design-files-1097281/

**Comment by Andrews54757** [comment]
they said it doesnt work

**Comment by JaraLowell** [comment]
Most websites you 'leech' wont work one two three directly on the server you move it to, nor do you get the whole functionality as you leech only the result, not what happens in the back to make said result. Specially if it be an dynamic page. So to it amazing for example that those that for example leeched mine, leave the google add sense code in for quite some time... mean seriously if you rip... that should be a first. But i would guess that shows how little people actually know about websites and just drag and drop just to have it without wanting to give credits to those that actually worked for it.
