### ISSUE TITLE
CANT CONNECT & CRASH.

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#123]
didnt edited anything, im getting this

http://prntscr.com/ak2lsy

**Comment by JaraLowell** [comment]
Bit weird, that is an WebSocket error, more; it means your client disconnected before disconnection could be send. Or something along those lines when google the error. Fire wall maybe ?

**Comment by skyleter** [comment]
I dont know, anyway idc i switched to my favourite ogarserv version [for me the most stable too], 1.6.2 xd

PS im the issue 123 :smile:

**Comment by JaraLowell** [comment]
hehe right now, the current git seems to be most stable, while we still ironing a few final kinks out. So 1.6.5 should be out soon when i am happy with it and its stability. Obviously the new physics drains a bit more over the old. But even with the new and skin support we now seem to have a rather smooth server that also stays lo in memory usage. Mean am over 1250 player cells created, at 12hour up time and it is peeked at 50Kb memory.
