### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by morenja** [JaraLowell/OgarServ#124]
I have some problems i use old protocol.
![screenshot_12](https://cloud.githubusercontent.com/assets/15367815/14064655/650c7758-f40b-11e5-8924-080e8af0fcee.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/15367815/14064657/651110e2-f40b-11e5-9f5f-0abda6893812.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/15367815/14064656/6510026a-f40b-11e5-9dd5-42fad939d483.png)

**Comment by JaraLowell** [comment]
That be a client issue,. not a server. And as we do not support none Agar.IO clients here on git, we can not help. That said, check the package received in regards of cell updates and update the client to the last protocol. And silly to use an old protocol while the new is only like 6 changes in the client.
