### ISSUE TITLE
Server shutdown time countdown to LB

### ISSUE THREAD

**Issue by mafiakb** [JaraLowell/OgarServ#126]
It does not work :(

**Comment by ghost** [comment]
Create a .bat file, and copy paste the code:
@echo off

rem **\* Please make sure node can be accessed at this phase, so either do a path to node. (see Dos manuals)
rem **\* or replace node by for example c:\path.to.where.node.is\node or if you wish to use JX replace node
rem **\* with JX.
rem **\* exemple: C:\JXCore\JX install..... etc

:loop
   cls
   node index.js
   goto loop

And start the server with this code.

**Comment by mafiakb** [comment]
My question is this line:
-                // Create a Time count down in a nice string and adds to LB
  -                var t = (this.startTime.getTime() + (this.config.serverResetTime \* 3600000))- local.getTime();
  -                var days = Math.floor( t/(1000_60_60*24) );
  -                if(days == 0) {
  -                    var minutes = Math.floor( (t/1000/60) % 60 );
  -                    var hours = Math.floor( (t/(1000_60_60)) % 24 );
  -                    hours = (hours < 10 ? "0" : "") + hours;
  -                    minutes = (minutes < 10 ? "0" : "") + minutes;
  -                    this.LBextraLine = ("~ ~ ~ ~ ~ " + hours + ":" + minutes + " ~ ~ ~ ~ ~ ~ ");
  -                }
    +

No work :(

**Comment by JaraLowell** [comment]
You only see the count down if day == 0 meaning 24 hours :smiling_imp: so if you put down 48 hours or more, you have to wait till 24h mark has bin reached for the msg to start showing up

**Comment by mafiakb** [comment]
Ohh, then in serverResetTime = 0? or day = 0

But, i have resetime in 3 ?, As you can Appear in three hours?

**Comment by JaraLowell** [comment]
serverResetTime = 24
