### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#127]
Hi programmers, i have 2 questions.
1.- How to change the zoom the cell?
That is.. ward off the camera of player.

2.- How do I change the "W" for small virus?
I have seen on multiple servers, instead of throwing mass, throwing small viruses with the "W" key, it is possible, no?

That is all, i hope someone clarify my doubts. Thanks :p

**Comment by JaraLowell** [comment]
PlayerTracker.js deals with zoon levels of players. Although it seems some clients have mega issues with some of the ways new servers send the map size date. 

It in one of the game mode's you dont turn it on by default as that would be stupid. The w key thing that is.

**Comment by makandz** [comment]
There is a mode called virus off..
