### ISSUE TITLE
how add skin food?

### ISSUE THREAD

**Issue by mafiakb** [JaraLowell/OgarServ#128]
// function Food() {
    Cell.apply(this, Array.prototype.slice.call(arguments));
    this.cellType = 1;
    this.name = '';
    this.skin = '%gas';
    this.size = Math.ceil(Math.sqrt(100 \* this.mass));
    this.squareSize = (100 \* this.mass) >> 0; // not being decayed -> calculate one time
    this.shouldSendUpdate = false;
    if (this.gameServer.config.foodMassGrow && Math.floor(Math.random() \* 201) > this.gameServer.config.foodMassGrowPossiblity && this.gameServer.run) {
        this.grow();
    }
//}

no working :(

**Comment by JaraLowell** [comment]
Food skin i ignored as that is a lot of calls made,. and migh cause lag to the server (if you have 3k food that is 3k name/skin check. If you want to enable that you need edit the UpdateNodes file. But would higly advice against it
