### ISSUE TITLE
adding sounds ?

### ISSUE THREAD

**Issue by matrixreal** [JaraLowell/OgarServ#13]
Hi,
is it possible to add sounds when :
1- eat cells
2- split
3- feed
4- gameover

thanks

**Comment by makandz** [comment]
That's client sided. So you need to add it to your client.

**Comment by matrixreal** [comment]
@MastaCoder 
okay thanks for quick reply

can you show us lines related too ...
also is your client / server mobile supported ?

**Comment by makandz** [comment]
My client isn't mobile supported :/ I use a different main_out.js for my client, so I looked into the Cigar client and I found this:

case 32: // Split Code
                if ((!spacePressed) && (!isTyping)) {
                    sendMouseMove();
                    sendUint8(17);
                    spacePressed = true;
                }
                break;
            case 81: // Q Code
                if ((!qPressed) && (!isTyping)) {
                    sendUint8(18);
                    qPressed = true;
                }
                break;
            case 87: // W Code
                if ((!wPressed) && (!isTyping)) {
                    sendMouseMove();
                    sendUint8(21);
                    wPressed = true;
                }

That's the code for w, space, and q. I don't know eat or death yet :/

**Comment by JaraLowell** [comment]
Sounds would be needed to the cell code, reader; and will cause a lot of sound specially for cells eating;

**Comment by matrixreal** [comment]
@JaraLowell 
maybe ... but i try it with the custom client of agariomods and its pretty fun

**Comment by matrixreal** [comment]
@JaraLowell 
any news please ? thanks

**Comment by JaraLowell** [comment]
This is the server side here, Sound would not be send by the server but be handled by the client. You would need to edit the java source for the client that one events that something happens an audio file is played. HTML 5 has support for that. However you would need find a coder for your client to do so. As right now most clients out there are different and would not be per say after be compatible with Agar.io
