### ISSUE TITLE
how add this virus?

### ISSUE THREAD

**Issue by mafiakb** [JaraLowell/OgarServ#130]
@JaraLowell this format virus how add?

![image](https://cloud.githubusercontent.com/assets/12769609/14286870/37153f44-fb16-11e5-8db8-fc7f2bf463bd.png)

**Comment by JaraLowell** [comment]
You can enable them in your config file by adding
`virusSpirals = 1`
0 to disable or 1 to Enable virus ejected mass spirals

**Comment by mafiakb** [comment]
Ty :)
