### ISSUE TITLE
How add point in leaderboard?

### ISSUE THREAD

**Issue by mafiakb** [JaraLowell/OgarServ#131]
Add point here in the standings ?

one imagen as reference

![image](https://cloud.githubusercontent.com/assets/12769609/14301397/22081120-fb5d-11e5-9c78-b5d1e03f8565.png)

**Comment by JaraLowell** [comment]
Edit Leader Bord file?

**Comment by mafiakb** [comment]
edit updateleaderboard.js?

**Comment by JaraLowell** [comment]
Yah, though would not see why as most nobody has 2~3 letters names; So would make it look rather weird with long names that not fit on the leader board. Hense why nobody does it.

**Comment by mafiakb** [comment]
yes. but is for mode games new, tournament only tag clan, CLAN WAR only TAG!

**Comment by JaraLowell** [comment]
so.. teaming :smiling_imp:

**Comment by mafiakb** [comment]
@JaraLowell  how add please :(
