### ISSUE TITLE
When the next update come.

### ISSUE THREAD

**Issue by ortex112** [JaraLowell/OgarServ#134]
When the next update come.

**Comment by JaraLowell** [comment]
Am testing some of the current server. Am so far pretty happy with it,. Or least on my server. Running it at a 32K map and 9K food. etc.. So a big world; And seems to stay pretty stable even when hitting above 35 players. Admit-tingly have to say though, more players is a lot more bandwidth. So if tests go well, i should make a new release within the coming days.
