### ISSUE TITLE
Better BOT IA?

### ISSUE THREAD

**Issue by J0113** [JaraLowell/OgarServ#136]
I really like OgarServ so I'll keep using it, but the bots are sometimes really stupid, is there any way to create a better bots?

**Comment by JaraLowell** [comment]
Bots are suppose to be a wee bit stupid, as in end you should not really use them. :imp: if they go be all smart and have a like near human approach to things, you gone be having a lot of unhappy new players. :laughing: So to the more smarter you make them, the more server time they eat. I would gues it is why they are as they are as we only give them like 5% of server tick time.

**Comment by J0113** [comment]
Jara, is that possible in the config soon?
