### ISSUE TITLE
Remove black message color?

### ISSUE THREAD

**Issue by makandz** [JaraLowell/OgarServ#14]
I am not sure if this is client sided or server sided. But I will guess it is server sided because the spectator name color always ends up grey.

I wanted to know how I can remove the black name from the chat. In dark mode you can't see the name well enough.

**Comment by ghost** [comment]
you can change the color from here in RGB format

https://github.com/JaraLowell/OgarServ/blob/6c06516ef9eb83cab5e229de10281d6673cfe01e/src/packet/Chat.js#L20

**Comment by makandz** [comment]
How about the player chat colors? That one was for spectators :+1:

**Comment by JaraLowell** [comment]
Players color the client gets from the color of the in game bubble, so that would need an edit in client to change. For Spectators i server side set there bubble to 'grey' :D

**Comment by makandz** [comment]
lol For some reason the name ends up black for a couple people. Is that just my clients issue?

**Comment by ghost** [comment]
can you show a screenshot ? i never saw a black color

**Comment by JaraLowell** [comment]
yes, there a bug in the chat for some of the "client codes" where the value is made wrong (if i remeber correct). for example ... 00 12 88 would result int hose client to " 12 88 " as int ( 001288 ) = 1288 but the 00 in hex is needed so you need compare my client with yours in regards of chat colors there player ball usually is black then to

**Comment by makandz** [comment]
The chat color is handeled in main_out.js correct?

**Comment by JaraLowell** [comment]
Right  :+1:
