### ISSUE TITLE
Change "<skin name>" for "||| skin name"

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#140]
Hi programmers, i have a question.
OgarServ comes by default the "<NameOfSkin>", So that is not seen on the client, that is, to make it look invisible. But I would like to change to make it "||| NameOfSkin". How is it done?
I hope to answer, thank.

**Comment by Barbosik** [comment]
Look at https://github.com/Barbosik/MultiOgar it supports skins if you enter name as "< skin name > player name". For exampel: "< shark > Fish" (remove spaces)
