### ISSUE TITLE
Callback argument must be a function

### ISSUE THREAD

**Issue by SirFulgeruL** [JaraLowell/OgarServ#141]
Hello  , 
a friend told me about this server and I wanted to install it . 
I am using Debian 3.16.7-ckt20-1+deb8u3 64 bits . 
And I get this error when I try to start it .

http://prntscr.com/b1sgwf

**Comment by Andrews54757** [comment]
see https://github.com/AJS-development/Ogar-unlimited/issues/508

**Comment by SirFulgeruL** [comment]
It didn't helped me .. I have Node version 6 something ..

**Comment by JaraLowell** [comment]
Try removing the modules folder and then downgrade your node version, then re install the node modules see if that fixes it for you.

To change your node version:
sudo npm cache clean -f --force
sudo npm install -g n
sudo n 0.10.43

then do 
npm install ws http fs sys mysql url underscore vector2-node
inside the folder where you run index.js 

then
node --nouse-idle-notification --expose-gc --always-compact --max-new-space-size=2048 --max-old-space-size=2048 index.js
