### ISSUE TITLE
Jara, I need to have your opinion

### ISSUE THREAD

**Issue by Andrews54757** [JaraLowell/OgarServ#143]
Hello, so in https://github.com/AJS-development/OgarUL-Plugin-Library/issues/6#issuecomment-219546973, me and entarr was having an argument about the pros and cons of a master server. I want you, the creator of the first MS to tell me your opinion

**Comment by EnTerr** [comment]
`<sigh/>`
See also more at https://github.com/AJS-development/Ogar-unlimited/issues/606#issuecomment-219555808

**Comment by JaraLowell** [comment]
the `pros` are, that players can find your server or a server to play on. But this only works if your mind set is that you provide a service to people and not care if it brings in money, the goal be there to have people find a moment of joy without the hassle of having to find a website that offers it.

the cons.. in that is, bad configured servers listed, and so to; website owners not per say getting there 0.01 euro cent as a player uses a other portal to get to there game service.

In a world so addicted with advertisement, and money from it; gaming websites seek to be unique and seek to be the only service, if be why game publishers that use canvas and websites seek to be the only one providing that game so the revenue from advertisement is from there side only. So to there noting wrong with that per say, as in end; web servers need power and upgrades once a whole to stay working.

So there lays your choice and it not you as ogar creator that makes that choice, it is the server admins that do. They decide how and what they intent do do with your software. They either can use a tracker or not; As it is them in the end, that provide the service and choose how they provide it.

**Comment by Barbosik** [comment]
**JaraLowell**: They either can use a tracker or not; As it is them in the end, that provide the service and choose how they provide it.

This can be easy solved just by adding option to ogar server config to enable/disable self registering on the tracker. And it will be better to specify tracker list which should be used.
