### ISSUE TITLE
Bots Issue's

### ISSUE THREAD

**Issue by raphyjb** [JaraLowell/OgarServ#145]
Poeple play with bots in my server
I see it does (1) (2) to the connecting per ip... at then at 20 ( i set it to 20 per ip ) if they disconnect they cant join back again... 
Also having another problem... Poeple for no reason disconnects... joins back and aint happy they got kicked.
Try my server you will see, also try put bots: ws://184.75.135.247:4411
Trying to run a 24/7 server here got alot of problems if u could help me by skype: raphy.jb 
if anyone could help, i would appriciate it alot! Thanks for reading!

**Comment by Andrews54757** [comment]
lol.

**Comment by JaraLowell** [comment]
i never understand why people in a small mass multiplayer game need bots; it in end down right sad and so what you got big by bots and have no life and nobody wants to play with you cause you a dishonorably player. 

Clients that disconnect and re connect usually have not clean connection as you nowhere in your client told the client to 'delete' the old connection; So client side can lag if you get disconnected and reconnect. So have a look at your client and clean the connection on disconnect.

**Comment by raphyjb** [comment]
What do you mean i need clear logs? not sure wat to do here...
anyways... even if its shit poeple use bots... i still want poeple to be alowed to join even if max connec per ip is 20.. but for now i need restart whole server each 2 hours or so cuz poeple skyping me.. hey can  you refresh i cant join anymore...

**Comment by JaraLowell** [comment]
They can reconnect they just need wait for the disconnect time out to finish. When you disconnect the server keeps you for like x seconds in the loop. Default i believe is like 300 seconds.

**Comment by raphyjb** [comment]
how can we ban bots? without banning the user?
btw ive put disconnect time to 0, ill try it out

**Comment by raphyjb** [comment]
Doesnt work. connected my bots then i disconnect... then try to connect back again and it keeps saying connecting...

**Comment by JaraLowell** [comment]
How can agar.io connect when we not compatible with there new protocol ? And reason why i have agar.io banned as origen as 95% of botting people come from there.

check `playerlist` to see how long a user is still connected for.

**Comment by raphyjb** [comment]
Hm where do i find that in gameserver? not sure if we have the same thing now... 
I have Ogarserv64, can u just join my server maybe u will know?

**Comment by raphyjb** [comment]
could u just skype if u got time?

**Comment by Andrews54757** [comment]
@raphyjb Add scramble

**Comment by makandz** [comment]
@Andrews54757 Coordination scramble sucks. People can still connect with bots to the server again with it. Even if the bots don't go to the player (which many people already made fixes so they do), they are still flooding the server. I can join a server, not give a single crap where the bots go and just flood the server. Scramble doesn't fix the bots issue at all.

**Comment by Andrews54757** [comment]
In reality, bots cannot be avoided. Even with my special anti-bot system, It still floods the server. (although you dont see them) like a DDoS attack. So i suggest mabye using a DDoS protection service (cloudfare?) .

**Comment by Andrews54757** [comment]
Also, bots evolve as protection methods evolve. My mouse filter and scramble and other things might protect Ogar UL for a short time, but there are ways to overcome it. So i recently just thought of a new, better anti-bot system

**Comment by makandz** [comment]
@Andrews54757 Yep you're right. I feel like their will never really be a way to stop bots. As they join pretty much like real players. What's your new idea?

**Comment by Andrews54757** [comment]
It wont stop the ddos attacks but it would pretty much make bots useless except for ddosing

**Comment by raphyjb** [comment]
Andrew can i have your skype? need advices.
