### ISSUE TITLE
All I see is the grid 

### ISSUE THREAD

**Issue by Churro123** [JaraLowell/OgarServ#146]
I have hamachi open, my skype is closed, and i put the ip and port it gave me...

Downloading agario.core.js...
/agario.core.js:7 Running...
/agario.core.js:7 postRun
/agario.core.js:7 
main_out.js:4 loggedIn with G+!
http://agar.io/mraid.js Failed to load resource: the server responded with a status of 404 (Not Found)
assets.tapad.com/idsync-1.1.2.js:57 initPixelsRequest with
assets.tapad.com/idsync-1.1.2.js:57 Request Group
assets.tapad.com/idsync-1.1.2.js:57 Requesting index
2assets.tapad.com/idsync-1.1.2.js:57 Requested image
2assets.tapad.com/idsync-1.1.2.js:57 Image error
assets.tapad.com/idsync-1.1.2.js:57 -- All requests ready
assets.tapad.com/idsync-1.1.2.js:57 -- Group finished
assets.tapad.com/idsync-1.1.2.js:57 2 Pixel requests: 215.048ms
VM5289 main.html:22 300
VM5289 main.html:65 useHeader = false
VM5289 main.html:74 totalAnimFrames = 3
VM5289 main.html:111 document.body = 
VM5289 main.html:112 [object HTMLBodyElement]
VM5289 main.html:156 startAnim()
VM5289 main.html:163 FRAME 1
VM5289 main.html:170 FRAME 2
VM5289 main.html:184 FRAME 3
3VM5289 main.html:221 highlightCTA
/agario.core.js:9 WebSocket connection to 'ws://25.15.94.204:4411/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
VM5289 main.html:221 highlightCTA
/agario.core.js:7 exception thrown: IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-30971) is negative.,Error: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-30971) is negative.
    at Error (native)
    at Array.<anonymous> (http://agar.io/agario.core.js:9:6078)
    at c.Ja._2b70ff1c (http://agar.io/agario.core.js:9:89629)
    at dc (http://agar.io/agario.core.js:10:17684)
    at oc (http://agar.io/agario.core.js:10:34270)
    at nc (http://agar.io/agario.core.js:10:33072)
    at Array.Rc (http://agar.io/agario.core.js:10:82682)
    at wr (http://agar.io/agario.core.js:13:2655)
    at Object.m.C (http://agar.io/agario.core.js:7:5793)
    at http://agar.io/agario.core.js:6:495c.printErr @ /agario.core.js:7
/agario.core.js:9 Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-30971) is negative.

(sometimes a very long list of errors pop up)

**Comment by JaraLowell** [comment]
Error losg shows one real thing `ERR_CONNECTION_REFUSED` meaning it refused it. Either Firewall, Gameserver or other reason. Hard to say without more info.

We right now do not support agar.io as they changed there whole protocol. So for now use ogar.mivabe.nl/?ip=`your ip`:`your port`

**Comment by Churro123** [comment]
Is it the port i got from ogar cmd?

**Comment by Churro123** [comment]
Can i change settings on that that too?

**Comment by JaraLowell** [comment]
Server settings are not in the client; but on the server :smiling_imp:
