### ISSUE TITLE
how to ?

### ISSUE THREAD

**Issue by matrixreal** [JaraLowell/OgarServ#15]
hi
i would like to know what are steps to install this server ?
thanks

**Comment by ghost** [comment]
https://github.com/JaraLowell/OgarServ/wiki/Manual-Installation

**Comment by matrixreal** [comment]
thank you
how ever ... it look dizzy. Grids are blinking.in mobile idevice retina display (iphone)
<img width="260" alt="retina" src="https://cloud.githubusercontent.com/assets/6823974/11396942/c639bd52-9375-11e5-88cc-4214b0dba2df.png">
any solution please ? thanks a lot and like your server

**Comment by makandz** [comment]
That's your clients fault not OgarServ's

**Comment by matrixreal** [comment]
yes ... do you have any idea please ?

**Comment by matrixreal** [comment]
@MastaCoder 
Hi,
i did exactly what is written
here what i got
![error](https://cloud.githubusercontent.com/assets/6823974/11414716/ea83d444-93f8-11e5-9dcc-6e141d4fcfbc.png)

**Comment by matrixreal** [comment]
now it run good but i think my client is not compatible
does any one have link to good client with this server please ?

**Comment by ghost** [comment]
this will work for you https://github.com/OgarProject/Ogar

ogarproject should work with your client

**Comment by JaraLowell** [comment]
Or he reads the config and changed the version OgarServ supports both old and new protocol just need to tell it so. See "serverVersion: 1" in [Server Config](https://github.com/JaraLowell/OgarServ/wiki/Server-Config) on how to do so wiki

**Comment by matrixreal** [comment]
i want to use the new protocol so 1 because it's updated and i see some example ... its far better and faster
but the problem is that i don't find a good client wich is optimized for it ...

**Comment by JaraLowell** [comment]
Well i cant help with that i fear; i only make OgarServ, the client is peoples own responsibility. The new protocol supports Agar.io so you then can access it trough http://agar.io/?ip='your ip':'your port'

**Comment by matrixreal** [comment]
thanks a lot really appreciate your effort and i like your OgarServ as it has many optimization and bug fix
also it's easy to manage and clean code
i'm planing to made an ios app so i can't use agar.io since it will redirect to their app on the store if the website is runing under idevice that's why i'm looking for a client
anyway thank you

**Comment by mdluffy01** [comment]
need client

**Comment by matrixreal** [comment]
yes we all need client compatible with v2 of this fork wich is great
