### ISSUE TITLE
Master server improvement

### ISSUE THREAD

**Issue by Barbosik** [JaraLowell/OgarServ#151]
Jara, could you please add new server type: -1
It means multi-protocol, it supports all known protocols: 4, early 5, late 5, 6, 7

Currently there are only two types:
0 - Private (protocol 4)
1 - Agar.io (protocol 5)

so, it will be better to extend it with -1:
-1 - Multi (any protocol accepted)
0 - Private (protocol 4)
1 - Agar.io (protocol 5)
2 - Vanilla (protocol 6)

I just want to add master server ping into my MultiOgar server: https://github.com/Barbosik/MultiOgar

PS: also it seems like ogar.mivabe.nl client has some issues with minimap. Could you please fix it?

**Comment by JaraLowell** [comment]
This is a good idea, and for sure one am willing to add, downside is, we have a lot of people using older git versions and not updating so; For them we would get at times an faulty reading. But for sure an interesting concept to add for the next final release.

**Comment by Barbosik** [comment]
I added your tracker into my server: https://github.com/Barbosik/MultiOgar/
There is no way to indicate server type, so I added "[*]" before game mode for my server.

I found some issues with ping data provided for tracker:
- there is need for server name field (not DNS, just a unique user defined name for ogar server). Current field "name" cannot be used, because IP:PORT is replaced with it's value, and user will be unable to connect;
- there is need for server type field to indicate type of server (for example Ogar, OgarServ, MultiOgar);
- there is need for bot count field;
- string concatenations for post request looks terribly, it will be better and easier to format it in JSON, for example, current code:

```
var data = 'current_players=' + this.sinfo.players +
                   '&alive=' + this.sinfo.humans +
                   '&spectators=' + (this.sinfo.spectate + this.sinfo.death) +
                   '&max_players=' + this.config.serverMaxConnections +
                   '&sport=' + this.config.serverPort +
                   '&gamemode=' + this.gameMode.name +
                   '&agario=' + pversion +
                   '&name=' + sName +
                   '&opp=' + myos.platform() + ' ' + myos.arch() +
                   '&uptime=' + process.uptime() +
                   '&start_time=' + this.startTime.getTime();
```

it will leads to parsing errors if some string cosists of special characters, such as '&', '=', etc.

With JSON it's much easier, clean, safe and extensible:

```
var dataObj = {
    "current_players": this.sinfo.players,
    "alive": this.sinfo.humans,
    "spectators": this.sinfo.spectate + this.sinfo.death,
    "max_players": this.config.serverMaxConnections,
    "sport": this.config.serverPort,
    "gamemode": this.gameMode.name,
    "agario": pversion,
    "name": sName,
    "opp": myos.platform() + ' ' + myos.arch(),
    "uptime": process.uptime(),
    "start_time": this.startTime.getTime()
};
var data = JSON.stringify(dataObj);
```

You can add second url for JSON version if you want to support old servers. 
For example, http://ogar.mivabe.nl/master-json

**Comment by JaraLowell** [comment]
Right now not gone json it; As it works as is.

I upgraded the tracker site, now also showing server version. See my git for howto. And updated the protocols to show more correctly. Using the 0,1,2 and 100 for multi protocol. :smile: 

Apparently i had left+right and not right-left in minimap; should i think be fixed now :smiling_imp:

**Comment by Barbosik** [comment]
Thanks. 
But it seems that agaio field (protocol) doesn't works. It still accepts true or false. I tried to set agario=100, but server tracker shows "Protocol 5"

And could you please split server name and server ip columns on the tracker?
Currently server tracker replaces server IP with server name. So, when I send server name "My Server", server tracker shows invalid server IP - "My Server" instead of server IP
I think it will be better to just replace country name with server name and show just country flag instead of country flag + country name, it will reduce table width. You can add country name in the hint for country flag image

**Comment by JaraLowell** [comment]
Yep saw, for some fun reason i forgot to change it in the ping to accept 2 and 100 :smiling_imp: should be fixed now.

For just showing IP, dont write down a name,. The name is to link to your own homepage slash client. It not for writing cute names :smile:

**Comment by Barbosik** [comment]
okay, so could you add server name field? Not dns, but just user defined name, such as "My Cool Server" :)
For old servers which don't send server name, just display empty value.

The server name helps to distinguish different servers, especially if a lot of servers hosted on the same dns (just different port).
It's the same as player name helps to distinguish different players, because just different color with no name is not enough.
