### ISSUE TITLE
Minimap bug

### ISSUE THREAD

**Issue by Barbosik** [JaraLowell/OgarServ#153]
There is a bug with minimap on ogar.mivabe.nl, could you please fix it?
For example just try to play: http://ogar.mivabe.nl/?ip=149.56.131.181:24270

See how to fix here: https://github.com/Barbosik/MultiOgar/issues/66

**Comment by JaraLowell** [comment]
Actually made a small boo boo it seems, seeing i always figured people start with 0 as left position and bottom. So instead of right - left i had + :imp:

**Comment by Barbosik** [comment]
shifted border, such as left=0, right=0 leads to errors in some cases, these errors looks like player just cannot play the game sometimes, because his mouse works incorrectly. It happens when scramble is enabled, or just when border has too large size.
So, I just removed borderLeft/borderTop/borderBottom/borderRight variables from config and replaced it with borderWidth and borderHeight. It works safe and easier for the user, and also works faster, because it uses precalculated border size.

**Comment by JaraLowell** [comment]
Thats also because you can only have an max number of x size / y size

int8   : -128 to 127 
int16  : -32768 to 32767 
int32  : -2147483648 to 2147483647 
int64  : -9223372036854775808 to 9223372036854775807

so basically as most use int16 max map size then would be 32767, INCLUDING scrambler add or you go out of bounds and get an error

**Comment by Barbosik** [comment]
Don't forgot about mouse message. It uses int16 (-32768..32767) to specify point on the map. And client sends it's coordinate with scrambling offset. It means that with not any scramble offset can be used. 

It's the reason, why with some scrambling value mouse works incorrectly. For user point of view it looks like server doesn't respond to mouse control sometimes. But after reconnecting it works again.

You can look into MultiOgar implementation it support scrambling for all protocols and for all clients. It also support scramble level 3, when server sends NaN for border and works with no border at all, so bots cannot calculate offset and descramble coordinates.

**Comment by JaraLowell** [comment]
OgarServ does not support scrambler nor will add it,. it pointless to have;

**Comment by Barbosik** [comment]
yes, I know. I talked about `serverScrambleLevel = 0` and `serverScrambleLevel = 1`, where minimap working ok. Currently I enabled `serverScrambleLevel = 2` on my servers to prevent minions. This mode is incompatible with minimaps
