### ISSUE TITLE
mivabe server gameserver.ini configuration ?

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#155]
Hi, i am sorry for open issue here but there is no place to want something.
@JaraLowell could you please share http://ogar.mivabe.nl gameserver.ini configurations ? Thanks

**Comment by JaraLowell** [comment]
That server runs on a modded server; changing the start colors of viruses and things as well changing the amount of alive viruses in map in the game mode experimental 2, so you wont get the same with just the ini.
