### ISSUE TITLE
white screen not connecting

### ISSUE THREAD

**Issue by NicholasNDB** [JaraLowell/OgarServ#156]
I start the ogarserv64.exe and it opens cmd, like normal. i then copy the hamachi ip and then go to the server i created. i type in my name and click play. the screen turns white and nothing happens, just a white screen, sometimes a white screen with graph lines in bckground. I then went to the cmd window and typed playerlist then hit enter. it shows that i connected, but i have a blank white screen. can you help with this issue

**Comment by NicholasNDB** [comment]
i just tried redownloading the latest version, and clicking play just seems to reload the page so i can click play again

**Comment by ItzLevvie** [comment]
Which client are you connecting through?

**Comment by JaraLowell** [comment]
Am working on switching to MultiOgar, however as i want it to have the same game modes as well what we already have it takes a bit of time to add and smooth out some kinks.

**Comment by JaraLowell** [comment]
lol, Levvie; 'has no memory leaks' your a bad liar, seeing i tested it; after one hour with 200 users connected you will see it has a HUGE memory leak. Testing it with bots is cute, but shows noting really as bots do not use a real socket. Test it for real and speak again.

**Comment by ItzLevvie** [comment]
Haven't had any issues with memory leaks on MultiOgar.. it could be your configuration

**Comment by JaraLowell** [comment]
Would say describe memory leaks so to :3 Memory (rss)  should never be above 100kb when only running for 24 hours and a good 500 connections later.
