### ISSUE TITLE
Contact with the developer

### ISSUE THREAD

**Issue by AkatsukiNova** [JaraLowell/OgarServ#157]
Hey,

Do you guys have the developer E-mail or Skype?

**Comment by JaraLowell** [comment]
Welcome to Github! and why would you need the email from the developer? :3

**Comment by mafiakb** [comment]
Jara Lowell whait is u skype?

**Comment by AkatsukiNova** [comment]
Hey,

My Skype is: Theimad9

Verzonden vanuit Outlookhttp://aka.ms/weboutlook

---

Van: mafiakb notifications@github.com
Verzonden: zondag 6 november 2016 01:18
Aan: JaraLowell/OgarServ
CC: AkatsukiNova; Author
Onderwerp: Re: [JaraLowell/OgarServ] Contact with the developer (#157)

Jara Lowell whait is u skype?

##

**Comment by JaraLowell** [comment]
mine is same as it is here 😃 not that hard to fings lol, just seurch for jaralowell

**Comment by AkatsukiNova** [comment]
Verzonden vanuit Outlookhttp://aka.ms/weboutlook

---

Van: Jara notifications@github.com
Verzonden: zondag 6 november 2016 16:01
Aan: JaraLowell/OgarServ
CC: AkatsukiNova; Author
Onderwerp: Re: [JaraLowell/OgarServ] Contact with the developer (#157)

mine is same as it is here ?? not that hard to fings lol, just seurch for jaralowell

##

**Comment by AkatsukiNova** [comment]
Heb je iets binnen al?
