### ISSUE TITLE
Problem with lag

### ISSUE THREAD

**Issue by justadev-afk** [JaraLowell/OgarServ#16]
After 50 alive this server is lagging
Why?

**Comment by JaraLowell** [comment]
We have people hosting with more then 50, alive; Might it be the machine your hosting it on can not actually handle 50, or bandwidth is not high enough to do so?

**Comment by justadev-afk** [comment]
128gb ram
1000Mb connection
Ovh

**Comment by JaraLowell** [comment]
mean CPU power, if the host it be on is running more then one service, it then obviously might mean the OgarServ gets not enough CPU cycles to handle 50+ on your end. If on linux check with 'top' the resource usage.

**Comment by justadev-afk** [comment]
Intel  Xeon E5
2x E5-2630v3    16c/32t  
2,4 / 3,2 GHz

**Comment by justadev-afk** [comment]
Is more profitable separate server on multiple servers?

**Comment by JaraLowell** [comment]
Well like any game server, never wise to host multiple on one and same machine. As stated, best to check what CPU usage is and judge from that.
