### ISSUE TITLE
Hello version problem.

### ISSUE THREAD

**Issue by unblockedgamess** [JaraLowell/OgarServ#161]
Hello jara is in the old server files gameerver.ini
Version: 1
This version that supports my script
In the new multiogar system it does not exist.
How can we fix this problem.

**Comment by JaraLowell** [comment]
In multiogar, or current ogarserv your client has to send the correct protocol handshake (in your case four or five) it it fails to do so it will go wrong obviously.

Look in your client code for the package 254 handshake:
ws.setUint8(0, 254);
ws.setUint32(1, 5, true); <- 5 as protocol

**Comment by unblockedgamess** [comment]
Ok thank you I will try.
What is the best client with this server file?

**Comment by JaraLowell** [comment]
Best client be the one using protocol five or higher, as it also has skin support. Four should actually not be used no more. Sadly there some websites out there still that use protocol four.
