### ISSUE TITLE
BotPlayer.js error

### ISSUE THREAD

**Issue by skysea** [JaraLowell/OgarServ#165]
// Splitting conditions
        if (check.cellType == 0 &&.
            cell.getSize() > (checksize + 4) * 1.15 &&
            cell.getSize() < checksize * 5 &&
            (!split) &&.
            this.splitCooldown == 0 &&.
            this.cells.length < 3) {

I change and fix

// Splitting conditions
        if (check.cellType == 0 &&
            cell.getSize() > (checksize + 4) * 1.15 &&
            cell.getSize() < checksize * 5 &&
            (!split) &&
            this.splitCooldown == 0 &&
            this.cells.length < 3) {

**Comment by JaraLowell** [comment]
Will commit a huge update in a bit, just testing if it all fully working 😸

**Comment by skysea** [comment]
wow :)
thank you for answer
