### ISSUE TITLE
How to have the actions messages appear?

### ISSUE THREAD

**Issue by Niall7459** [JaraLowell/OgarServ#167]
I have the question:

How can i make the cell actions appear, like you do on ogar.mivabe.nl. Where it says such as:

Player eats Player (+10 mass)
Player eats Virus, Yumm!

**Comment by JaraLowell** [comment]
That's in the client; When you read the node update package, the first part of the package is killed cells it has the killer id and the killed node id.

**Comment by Niall7459** [comment]
Ok, I will give it a go!

**Comment by Niall7459** [comment]
This is by far the best agar server software!

**Comment by JaraLowell** [comment]
Also started a skype group, for more easy and or faster communications between server owners and users to gather more easy what might need fixing and or share ideas 

[Join us on Skype group by clicking this!](https://join.skype.com/bWtHKFC5DhTt)
