### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by matrixreal** [JaraLowell/OgarServ#17]
hi,
i know that i ask a lot ... but i have been searching since 3 weeks
can anyone share with me a client wich is compatible with the server protocol 1 (new one)
thank you

**Comment by ghost** [comment]
check your mail i have send you a mail

**Comment by matrixreal** [comment]
your email is not working good ... i send you messages sometimes you receive it and sometimes i get Delivery Status Notification (Failure)‏

**Comment by DeeJaVu** [comment]
please send a email to ocimscripts@gmail.com

**Comment by matrixreal** [comment]
@DeeJaVu 
any news ? please ...

**Comment by JaraLowell** [comment]
This here is only the Server, we support agar.io/?ip= as client. For any other clients, one should not ask her, but perhaps an forum more dedicated to that as ragezone :fast_forward:

**Comment by ghost** [comment]
sorry can't help
