### ISSUE TITLE
Why my leaderboard is missing? Using OgarServ and OgarClient

### ISSUE THREAD

**Issue by helma27** [JaraLowell/OgarServ#173]
Just as mentioned above, how to solve that?
And, if i use Test Server from Ogar.mivable.nl it visible

![alt text](http://image.prntscr.com/image/c4d0f72a4254490fb455ba1b3c1a1996.png "Leaderboard troble")

**Comment by JaraLowell** [comment]
Ah Using older OgarServ... lol; i need sent the new update to git >.< happens due LB not knowing if it needs to render unicode or ascci

**Comment by helma27** [comment]
ohhhh,,, lol... yeah, im using the git version, hahaha

**Comment by JaraLowell** [comment]
Update for OgarServer on Git now 😈

**Comment by helma27** [comment]
nice, its working now, btw, how to put command on the console?
is it removed now?

**Comment by helma27** [comment]
im using radmin, but the password is always says incorrect
`    { 
        "ip":"this is my own ip", 
        "password":"1234",
        "role":"ADMIN",
        "name":"Local Administrator" 
    },`

is this correct?

**Comment by JaraLowell** [comment]
"this is my own ip", need put your own valid ip there or a * to allow to connect from any IP

**Comment by helma27** [comment]
external ip or local ip?

**Comment by helma27** [comment]
nvm mind, it's solved 💃
