### ISSUE TITLE
Help ?

### ISSUE THREAD

**Issue by realhypex** [JaraLowell/OgarServ#174]
http://image.prntscr.com/image/83093a971bbc4abebfc185853589f72b.png
On my windows rdp

**Comment by JaraLowell** [comment]
Edit the start command file and remove `--max-new-space-size=2048 --max-old-space-size=2048` from the command line. New versions of node can not use this or more do not use this command any more.

**Comment by adib696** [comment]
Now
![](http://image.prntscr.com/image/6bee0361720a467e9e640d828ec5a46c.png)

**Comment by adib696** [comment]
Fixed it  
but i get this then it close fassst
took me 1mi to screenshot it
![](http://image.prntscr.com/image/17a1bc5a1ab745f981de1187d57e1a52.png)

**Comment by realhypex** [comment]
fixed it 
but i get this then it close sooooo fast 
took me 1min to screenshot it at the momment
![](http://image.prntscr.com/image/45569c9dd3f34d2ea3b07f7d79237645.png)

**Comment by adib696** [comment]
# Help :v:

**Comment by realhypex** [comment]
### btw i installed node modules using 
### npm install
### npm install socket.io-client

**Comment by JaraLowell** [comment]
would think something went wrong with your modules, you should only have to do npm install and then node index.js well after editing the gameserver.ini but yah. no need install socket.io

**Comment by realhypex** [comment]
same prob :(

**Comment by JaraLowell** [comment]
why you get 1.6.5 ? Just try last version on git >> https://github.com/JaraLowell/OgarServ/archive/master.zip

**Comment by realhypex** [comment]
didn't work :/

**Comment by adib696** [comment]
tried it on my pc too

**Comment by realhypex** [comment]
@JaraLowell 
![](http://image.prntscr.com/image/5ba101e90b4d438897d854ddf465082c.png)

**Comment by alivardar** [comment]
npm install module_name

**Comment by realhypex** [comment]
oooooooh forgot about that 
fk :v 
Ogar-feeder-bot probs Lol

**Comment by JaraLowell** [comment]
mmm did i forgot to add thatto npm installer.. need check later on . . .
