### ISSUE TITLE
Multicore?

### ISSUE THREAD

**Issue by Ciao121** [JaraLowell/OgarServ#18]
Hi,
it seems to me that multicore is not yet possible because the server launches different sessions and user are not in the same server? Am I right?

**Comment by JaraLowell** [comment]
JXCore by default launches in a muticore setup, however, it only so to speak places the a sync parts in a next core. So for OgarServ tha basically means the console is in 0, the server in 1 the web server if enabled in the next. If we wanted to be it based on player login it would need to be a total re write of the game server code and way it is handled. Though in end, we dont really seek to make it multicore in that way, if your OS is smart enough it is core spreading and or core switching even if it is a single application. Reason why we switched to JXCore is more the smoother memory handling and more stable over all node handling.
