### ISSUE TITLE
Sometimes bigger cell is faster than the smaller one.

### ISSUE THREAD

**Issue by happyhg3927** [JaraLowell/OgarServ#181]
While playing, sometimes i feel bigger cells are faster than smaller one and actually bigger one catches up smaller one. I don't know why, but can you fix it?

**Comment by makandz** [comment]
Anybody confirm?

**Comment by JaraLowell** [comment]
Would guess might be this at line 1139 in GameServer.js
```
// Speed up a little if we can merge
if (check._canRemerge) speed *= 1.25;
```
Removing it or setting it to 1.00; would remove the slight boost

**Comment by happyhg3927** [comment]
Okay, I'll try it.
