### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by justadev-afk** [JaraLowell/OgarServ#19]
Hi jaraima, I want to talk to you in private for business if you are interested contact me
juliosansossio@hotmail.com (skype)

**Comment by JaraLowell** [comment]
for business? how is a game server leading to business...

**Comment by justadev-afk** [comment]
It is a game that generates money, hence you commented q business

**Comment by justadev-afk** [comment]
Jaraima?

**Comment by JaraLowell** [comment]
It might generate money if you make a system to pay for something within the game. Mean google adds, it cute. But wont earn you money, over all you will still loose a good bit over the server costs vs the lo $ you get from adds.

**Comment by justadev-afk** [comment]
what I want is an improved version of the server, 100 usd? talk business
