### ISSUE TITLE
How to install on Centos6/7

### ISSUE THREAD

**Issue by oguz6578** [JaraLowell/OgarServ#20]
Centos6 minimal server installed.
- yum -y install wget git
- yum -y update
- reboot
- curl http://jxcore.com/xil.sh | bash
- cd /home/
- git clone https://github.com/JaraLowell/OgarServ
- cd /OgarServ/src/
- jx install querystring ws http fs sys mysql
- jx index.js

but

![image](https://cloud.githubusercontent.com/assets/16138958/11568199/8193fc56-99f3-11e5-859b-e258b5539151.png)

**Comment by JaraLowell** [comment]
I do not know noting of CentOS but i believe that message means OS outdated and needs to be upgraded to higher version. Checking the JXCore issues there are some reports there as well. An user posed that dooing `su -c 'yum update'` fixed the issue for him.

**Comment by ghost** [comment]
that has nothing to do with your os version, you cant do http://yourip:port to play the game.. you need a client if you want to host it on your own website or you can visit agar.io/?ip=yourIP:PORT to play with your own game settings

**Comment by oguz6578** [comment]
ok. How do I set up my client's own server?
like that http://ogar.mivabe.nl

**Comment by ghost** [comment]
like i said you need a cleint, you can find clients here http://agar.gcommer.com/index.php?title=Client_Implementations
