### ISSUE TITLE
OgarServ crashes as soon as i connect.

### ISSUE THREAD

**Issue by dragongoose** [JaraLowell/OgarServ#200]
im using the cigar client to connect to it. the server dissapears immediately as i connect.

**Comment by freaky767** [comment]
[MultiOgarII](https://github.com/m-byte918/MultiOgarII)
[OgarII](https://github.com/Luka967/OgarII)
both projects are updated frequently, and provide a ton of features. this hasn't been updated for years, so i'd suggest you use either MultiOgarII or OgarII.
