### ISSUE TITLE
Skins?

### ISSUE THREAD

**Issue by Dniel97** [JaraLowell/OgarServ#21]
When I host my Server and enter a Name that has officially a Skin, like "Earth", it only shows the color. I tried the OgarProject Server andthere it works fine, but the console of this server isn' t as good as yours. On you personal Client: http://ogar.mivabe.nl/ the skins are working fine.
![ogarserv 1 5 9 skins](https://cloud.githubusercontent.com/assets/6324072/11725131/58ac006a-9f78-11e5-8a05-f7a6aaaf65e5.png)

**Comment by JaraLowell** [comment]
The client checks if a skin file exists and is used. The server just relays the name one chooses, it adds noting nor removes or changes it; So you would need check in your client of the skins folder is accessible and if the client checks (case sensitive or not etc)

**Comment by Dniel97** [comment]
That's the problem; I don't have a akins folder. Could I create a "skins" folder and put a picture with .png in it? Why does it work without a skin folder by the OgarProject Server project?

**Comment by JaraLowell** [comment]
It client side, not server side; OgarServ works with the client that goes with your Server Project thingy. Just need make sure you set version right.
