### ISSUE TITLE
Minions

### ISSUE THREAD

**Issue by Edgeset** [JaraLowell/OgarServ#23]
How to fix this problem? They cover te server with stupid bots. Is there a wat to ban multiple IPs?

**Comment by JaraLowell** [comment]
This is one can say to max allow one connection per IP, but what if multiple people from one house wish to play? So to VPN and Browser proxy's can also get around this. You will in end always have dweeps with bots, even though  truly do not understand why. The game is simple, it a hour or two fun and you move on. why or how, is a bot making it fun other then people leaving and thus the bot-ter... playing alone.. mean really.. cu-does for them, but they must seriously have, no friends, that they need an digital one.

**Comment by Edgeset** [comment]
Thank for your reply, can you help me with max allow from one IP? Maybe set it to 30 not more from that ip

**Comment by ghost** [comment]
there is a feature in ogar called "coordinate scrambler" which will throw the bots all over the place and not let them go to one specific area. see this:
https://github.com/OgarProject/Ogar/commit/426a63757f17eb28f6738ed45434eb5cc3134e77
