### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by AgarioCheats** [JaraLowell/OgarServ#26]
I can't manage to get the hiscore functionality to work. Console logs MySQL error. My mysql.ini file is exactly as the example you set, and is located at /src/ with gameserver.ini.
Why does this occur? I did not change the 50 second connectivity which you mentioned. Could that be the problem?

**Comment by JaraLowell** [comment]
Can you show the log? As there can be a multiple of issues, The time out's from MySQL might be set to low. And do not start the server with any option is you run it with jxcore, so no adding multi etc. just jx index.js or it will fail as well

**Comment by AgarioCheats** [comment]
New MySQL error showing now:
MySQL Error!
Error: ER_BAD_DB_ERROR: Unknown database 'agario'

Do i need to manually create the database? If so, what columns to add?

**Comment by JaraLowell** [comment]
It might fail to create, if the user/pass you submitted to the ini file, has no 'rights' to create. It should create the database/table on start. But you will have to grand it access to create it. Or create it manually UTF8 and all that and see it it creates the table within the database.

**Comment by AgarioCheats** [comment]
By the way, regarding the server itself on a new host: Running a CentOS 6.4  and Nginx server and with a domain and the private server running, doesn't let me connect to the server. But if i use another domain and another host, for example ogar.mivabe or agar.io i am able to conncet. Any other host with the same client - i can connect to the server. But from the domain with the same host, i'm unable to connect to the server. Help! I have tried to disable Iptables, still doesn't work.

**Comment by JaraLowell** [comment]
Sound more like an DNS issue then anything else; Again my experience with CentOS is limited, so i would not know much about that.

**Comment by AgarioCheats** [comment]
Even if i connect to the server directly with its IP address, i still can't connect. 
---Figured out the problem was with nginx.

**Comment by AgarioCheats** [comment]
How would it be possible to log Total time played and Total mass gained (all time adds up) in MySQL?

**Comment by makandz** [comment]
I don't know how this can be done through Node.js, this has been open for a while so I'm just going to throw this out:

Maybe catch the data sent from the server and then add them using JavaScript's Math function to equal a variable and write that variable to the server?

Not sure though :/

**Comment by JaraLowell** [comment]
i still need fix MySQL; sending in then more info is not that hard; but right now current mysql can kill your SQL server really... i need poll it a bit but that is when all current updates are fixed and smoothed out :smile:
