### ISSUE TITLE
Banlist removed after restart?

### ISSUE THREAD

**Issue by AgarioCheats** [JaraLowell/OgarServ#27]
How can i make the banlist written to a .txt file and be read every time so that the IP's stay permanently banned, rather than having to manually enter them after every restart since they disappear from the banlist?

**Comment by JaraLowell** [comment]
Yah i need add this to the code to read, and write the ban text file on close and open. I shall add that to my to do things and prey i get an update out before xmas lol. But cant promise it!

**Comment by AgarioCheats** [comment]
Please do! And thank you!
Merry xmas!

**Comment by JaraLowell** [comment]
Added to git, will compile the release tomorrow
