### ISSUE TITLE
Automatic removal of bots

### ISSUE THREAD

**Issue by AgarioCheats** [JaraLowell/OgarServ#28]
How do i remove the function which removes bots? I'd like the bots to stay permanently.
Thanks.

**Comment by Edgeset** [comment]
-> gameserver.ini
serverBots = number of bots

**Comment by skyleter** [comment]
@Edgeset It does not mean that. He wants to keep the bots. In OgarServ if a bot dies = will dont back
Ill edit this comment if i found the solution

**Comment by Edgeset** [comment]
@mogokcp Oh sorry, my fault. BTW i've never had this problem

**Comment by ghost** [comment]
i have the same problem

**Comment by skyleter** [comment]
Fixed! 
I used the code from OgarProject. 
You need to go into gameserver.js (on Ogarserv folder/src).
Go to the line `80`. You will found a code like this one:

```
 // Respawn if bot is dead
    if ( this.cells.length <= 0 ) {
        var players = 0;
        this.gameServer.clients.forEach(function(client) {
            if (client.playerTracker && !client.playerTracker.spectate)
                players++
        });
        if ( players <= this.gameServer.config.serverBots ) {
            this.gameServer.gameMode.onPlayerSpawn(this.gameServer,this);
        }
        if (this.cells.length == 0) {
            // If the bot cannot spawn any cells, then disconnect it
            this.socket.close();
            return;
        }
    }
```

Change it to : 

```
    // Respawn if bot is dead
    if (this.cells.length <= 0) {
        this.gameServer.gameMode.onPlayerSpawn(this.gameServer,this);
        if (this.cells.length == 0) {
            // If the bot cannot spawn any cells, then disconnect it
            this.socket.close();
            return;
        }
    }
```

It will look like this:
![this](https://cloud.githubusercontent.com/assets/10405536/11942585/677d8b8a-a816-11e5-90b6-b525ce72b4df.png)

**_There is the proof :+1: -->**_
![.](https://media.giphy.com/media/xTk9ZZaKewtQbVLD8Y/giphy.gif)

**Comment by JaraLowell** [comment]
OgarServ used bot min players, so if you set it to ten it will keep ten bots in game, till you have ten real players. As most people do not really enjoy playing solo, but also do not like to play against bots all the time, seeing the bots are, well, not to smart. However indeed, the code from OgarProject does not use this future.

**Comment by ghost** [comment]
thanks a ton!
