### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#29]
I cant install any module on JXCore. It says i dont have jx custom path, now i've tried to create node.config on C:\Program files (x86)\JXcore. (theres no bin folder) and says this: http://prntscr.com/9gvnsx
node config : 
    `{
    "npmjxPath": "C:\Program Files (x86)\JXcore\jx.exe"
    }`

my batch file is 
    `@echo off
    jx install querystring ws http fs sys mysql
    :loop
    jx index.js
    goto loop`

Please help me im so NOOB in this. Thanks, if i dont explained good, i do not speak english.

**Comment by ghost** [comment]
I had the same problem. So what I did was downloaded the original build of ogar found in this link: 
https://github.com/OgarProject/Ogar/
Then I took ther "start.bat" from ogar-master then put it into the ogar-serv/jx build. And as long as you have node.js it works fine. look at this pic for more info : 
![capture](https://cloud.githubusercontent.com/assets/15255724/11940594/a9eeaea0-a7f7-11e5-884a-61b31f2ea73b.JPG)

**Comment by skyleter** [comment]
Thanks a ton :)

**Comment by skyleter** [comment]
![.](https://cloud.githubusercontent.com/assets/10405536/11940702/1b40c488-a809-11e5-800e-2065980ce020.png)
Im trying this, thanks again :)
**EDIT**
Im getting this. do you know why? 
Application couldn't start because of the configuration file is either corrupted or not accessible. [SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data]

**Comment by skyleter** [comment]
Nevermind.
