### ISSUE TITLE
Is this possible like in Agar?

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#30]
In OgarServ, can we do this? {add skin in my case bat.png -> bat (it will show the bat skin on my server)
![screenshot_6](https://cloud.githubusercontent.com/assets/10405536/11947198/738fe61c-a842-11e5-8ed4-5bc0081c84ab.png)
**but** when play, dont display "bat" at name...
In agario: bat.png (on /skins/premium) -> Does not display name 'bat' because is a 'shop' skin but i want to do the same thing on ogarserv, by just typing on nick 'bat' . ->clic play -> do not display name bat, just the skin

**Comment by JaraLowell** [comment]
That is client side, not Server; You will need to change that in your web client. This forum is only for OgarServ support not to any of the clients used.

**Comment by skyleter** [comment]
Thanks.
