### ISSUE TITLE
Cell removed after disconnection immediately

### ISSUE THREAD

**Issue by AgarioCheats** [JaraLowell/OgarServ#32]
Changed value to -1. Is now never deleted.
Hi, i've tried editing the setting in gameserver.ini, but doesn't change anything. Upon exit, cell is deleted frmo the game.
_

**Comment by makandz** [comment]
That is on the client that sends the server the information that the cell is dead.

**Comment by AgarioCheats** [comment]
I would of thought so, but it's not. It's a configuration setting in the playertracker which is wrong, so it removes the cell completely if the number is not -1. If it is -1, cell stays forever, and so does the connection of the user -> Which will eventually stay even if the user left, and spam the server with "ongoing connections" - taking playerspots even though they're not there.
Makan, do you use agar-clone for abs0rb?

**Comment by makandz** [comment]
Strange enough you might be right, we just have to wait for Jara to come see. Also yes I do, but it's quite heavily modified.

**Comment by AgarioCheats** [comment]
It must be extremely modified since Agar-clone is rather low-quality? Merged with Ogar?
Why not use Ogar/OgarServ?

**Comment by makandz** [comment]
What do you mean AgarioCheats?

**Comment by AgarioCheats** [comment]
What i mean is that it doesn't have as much functionality and ingame features as Ogar. For example, moving the mouse causes all the cells to move, rather than focusing on moving the cell closest to the mouse first.
