### ISSUE TITLE
new client ?

### ISSUE THREAD

**Issue by matrixreal** [JaraLowell/OgarServ#33]
hi all
can anyone share with us the new client ? compatible with the v2
thanks a lot

**Comment by ghost** [comment]
no

**Comment by matrixreal** [comment]
Hi all,
just needthe basic client that work with the v2 of the OgarServ
thank you

**Comment by makandz** [comment]
This is the issues of OgarServ not asking people for clients.

**Comment by JaraLowell** [comment]
OgarServ is just the Server as is, we not here to go and share clients or repair slash fix client issues. There are other forums for that.

**Comment by matrixreal** [comment]
ok no problem ...
but i did search all the webs and didn't find about clients
can you share with us some website ? thank you

**Comment by JaraLowell** [comment]
http://forum.ragezone.com/
