### ISSUE TITLE
DISCONNECTION

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#34]
i get disconnected by a cell being "undefined" and its annoying. Regular Ogar doesn't do that. This build has a whole protocol in gameserver.js for "undefined" disconnections. Any way to disable/fix it?
![f6f71992-ad58-11e5-9a3c-6bfd450739c0](https://cloud.githubusercontent.com/assets/15255724/12043825/dd911bd4-ae56-11e5-912b-a99f15e18ed5.JPG)

**Comment by JaraLowell** [comment]
You killed him, while he was connected, and then if you use 'agar.io' it auto selects a new server and thus disconnects you. Undefined is not the server per say, but simple node not knowing that F5, or close tab, or close browser, is a normal exit.

**Comment by ghost** [comment]
i'll take that as a no. also how does eating a massive mothercell kill him? and that him is me.

**Comment by JaraLowell** [comment]
You issued the command killall, what basically is same as you dieing, The agar.io client at times go to a new server after that and thus disconnected you. Thats what the Undefined means, has noting to do with cells. But more that some browsers no send a close connection on browser close, adress change etc :)

**Comment by ghost** [comment]
it did appear to be only chrome that had the "undefined" problem. This issue will now be closed.
