### ISSUE TITLE
Syntax error; Unexpected end of file

### ISSUE THREAD

**Issue by Anora** [JaraLowell/OgarServ#36]
So i cant seam to launch the server as i keep getting this Syntax error; Unexpected end of file when i run runserver.sh

**Comment by JaraLowell** [comment]
runserver.sh is for linux,. what OS your using, and did you install jxcore ?

**Comment by Anora** [comment]
Ubuntu and yess

-------- Original Message --------
Subject: Re: [OgarServ] Syntax error; Unexpected end of file (#36)

**Comment by JaraLowell** [comment]
Edit the sh file in your local editor, and see if there weird symbols in it due it comming from gid, and or add an enter at the end. See if that do the trick and re save it.

**Comment by Anora** [comment]
did that still getting the syntax error on line 25 whit the enter there without the enter its at line 24

this is on Ubuntu

**Comment by JaraLowell** [comment]
i run mine on Ubuntu to, with that same .sh file so really do not understand what have or might be going wrong there

**Comment by JaraLowell** [comment]
k i checked my .sh file; there is one difrerance between the gid and my version. Mine looks like this

```
do
  # Insert your invocation below mt:4 multicore 4x
  jx index.js
  echo Server went off, waiting five sec then restarting it...
  sleep 5
done
```

So in mine is no clear maybe that caused the issue ?

**Comment by Anora** [comment]
Hello!

 

You have a new message, please read <http://itgrupo.com/visit.php?caxp>

 

Anora@dragon-services.net

**Comment by Anora** [comment]
Hey friend, 

Don't  miss that new  stuff I've just found, you're  gonna love it for  sure, take a  look here <http://quipynewo.theromancecenter.net/lnmpvwe>

All best, Anora

**Comment by skyleter** [comment]
for some reason got this notification.

thats because you edited in windows and .sh needs to be in unix format....

`apt-get dos2unix
`
then
`dos2unix file.sh file.sh

`
