### ISSUE TITLE
[Bug] Client tried to connect, but server player limit has been reached!

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#38]
I have 80 online and 200 online limit but server says "<199/200> Client tried to connect, but server player limit has been reached!"
how to fix this?

**Comment by JaraLowell** [comment]
When people get disconnected the timer to actually see them as gone starts. Once reached it then removes the player to give room to a new player. So it might say x alive, and x spectating yet has more slots in use. See playerlist to find out what might be going on.

**Comment by ghost** [comment]
Players doesn't removing from this.clients.
(1/200 Online, 15h uptime)
![screenshot_3](https://cloud.githubusercontent.com/assets/8215170/12324152/6fb73e16-bac9-11e5-8298-f57f2506aed3.png)

**Comment by ghost** [comment]
stats:
{"current_players":23,"alive":16,"spectators":7,"max_players":200,"gamemode":"Free For All","start_time":"2016-01-14T11:19:39.677Z"}

config:
playerDisconnectTime = 10

this.clients.length:
153

**Comment by helma27** [comment]
i had this problem too!

**Comment by JaraLowell** [comment]
mm actually see... i thought i fixed this once before.. as the count player.length... returns bogus values at times... >.> will RE fix that then lol
