### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#39]
Why ogarserv is using too much ram? (Screenshot it was taked in 50 Online player.)
![8pve2fn](https://cloud.githubusercontent.com/assets/8215170/12309590/2dd2fa82-ba54-11e5-9c52-3143bb0359b0.png)

**Comment by JaraLowell** [comment]
Whats the up time for that ? 1.5GB that is one serious mem leak, question is, where it leaking. Even that 914 i think is way to high Question is, is that due JX or due our small java code.

**Comment by ghost** [comment]
5-6 Hours uptime, i think problem in playertracker or socket.

**Comment by ghost** [comment]
fixed.

**Comment by JaraLowell** [comment]
How it got fixed? :yum:

**Comment by ghost** [comment]
Turn off the function stats2file.

```
function stats2file(gameServer) {
    return;
}
```

**Comment by JaraLowell** [comment]
Ah, yah not even need that no more as we got MySQL working now actually forgot that one was still active, will have that gone in next setup yep yep
