### ISSUE TITLE
Ogar Anti Teaming?

### ISSUE THREAD

**Issue by helma27** [JaraLowell/OgarServ#42]
Hi, Jara, do you have any idea to implement this feature to this server?

**Comment by JaraLowell** [comment]
Can't really `stop` teaming i fear mean by any logic, some body choosing not to eat up player x might cause to trigger it. And so to i think, the reason to have chat, it to make teams. Agar.io even has this whole team thing setup where you with a key get with your team. And how long is that fun for, a hour, maybe 2. As once a team gets to big; and people leave... said team is on it's own and well soon so to, will go. So i would say enjoy the game, and when you see teaming. Move on to a other server. There a hundred to choose from, if nor more.

**Comment by makandz** [comment]
Ogar just got an anti-team update. Maybe pull it from there onto OgarServ as an option in the gameserver.ini?

**Comment by Andrews54757** [comment]
Im currently working on a better anti team mmech on my fork though, it would take a while still.
the theory is that when people team, they exchange mass back and forth, so if x is an amount of mass, if it is passed back and forth within 2 players, it will give them a anti team effect. only problem is how the server "memorises" all those variables"

**Comment by helma27** [comment]
Wow... i need that on OgarServ Jara version :(

**Comment by Andrews54757** [comment]
Currently, regular ogar has anti teaming but not a good one, mine also has anti teaming but it isnt very good. I am trying to improve it

**Comment by helma27** [comment]
i try to implement by my self on Jara Serv, but i dont think it working, bcus my lack of JS language

**Comment by helma27** [comment]
@JaraLowell can you considering this?
