### ISSUE TITLE
Kick spectator after 5/10 mins

### ISSUE THREAD

**Issue by Edgeset** [JaraLowell/OgarServ#45]

**Comment by makandz** [comment]
I had the exact same idea. Might start testing, see if setTimeout works on node.js xD

**Comment by JaraLowell** [comment]
it actually not a grand idea, mean it cute; but dont forget, some use spectator mode to record a game. They not gone be to happy if you kick them mid recording.

**Comment by skyleter** [comment]
^

**Comment by JaraLowell** [comment]
Added in commit ca636dc
