### ISSUE TITLE
Super Food, Virus

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#46]
how can i do that?
![go4vqv](https://cloud.githubusercontent.com/assets/8215170/12536910/43208db8-c2bb-11e5-9815-018989223f06.png)

do you have any implementation for shoot virus when player press w?

**Comment by makandz** [comment]
That was made manually by the guy at agariohub.com. Also about the w thing, Ogar-Plus has it as a gamemode, just grab the gamemode files from OgarPlus to pull it straight to your Gameserver.js
