### ISSUE TITLE
Big Dark Blue random name when spawned

### ISSUE THREAD

**Issue by helma27** [JaraLowell/OgarServ#49]
Umm,,, can you help me, how to fix it?

![Image of Issue](http://i.imgur.com/N2JbLet.png)

**Comment by JaraLowell** [comment]
Server Version wrong? Thats client that no understand something. Usually happens with older clients. Try switch server to old mode.

**Comment by makandz** [comment]
Yeah it is. Check the gameserver.ini and change the serverversion to 0
