### ISSUE TITLE
Client...

### ISSUE THREAD

**Issue by J0113** [JaraLowell/OgarServ#52]
I like your project but how to setup a client? I saw [this](http://agar.gcommer.com/index.php?title=Client_Implementations) page but I don't know how to setup one of those! Can someone help me?
Ps. 1: I am dutch
Ps. 2: I don't want the official agario client
THANKS FOR ANY HELP!

**Comment by skyleter** [comment]
Be careful, using custom client is agaisnt Agar.io Terms Of Service. 

They can send a takedown request to close your server.

**Comment by JaraLowell** [comment]
OgarServ is only and only the server we do not give support to clients here.
