### ISSUE TITLE
Can't start on windows 10

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#53]
After this release is not working anymore for me...
`SyntaxError: syntax error (C:\Users\Tom├â┬ís\OgarServ-1.5.9\src\modules\CommandList.js 103:29)
    at Module.prototype._compile (module.js:591:25)
    at Module._extensions[".js"](module.js:651:1)
    at Module.prototype.load (module.js:442:7)
    at Module._load (module.js:407:5)
    at Module.prototype.require (module.js:477:10)
    at require (module.js:495:12)
    at C:\Users\Tom├â┬ís\OgarServ-1.5.9\src\index.js:2:16
    at Module.prototype._compile (module.js:621:10)
    at Module._extensions[".js"] (module.js:6
Presione una tecla para continuar . . .

`

**Comment by skyleter** [comment]
PS im using ogarserv 1.6.0, didnt renamed folder

**Comment by JaraLowell** [comment]
The executable or or using node or jx ? (I my self use jxcore on windows 10 and works perfect for me)

**Comment by skyleter** [comment]
Sourcecode with a bat 
`@echo off
jx index.js
pause`

---

i have the .sh also. I installed the needed things with npm, because with JXCore gives me this: 
 \ http://prntscr.com/9wmaa2 \

module files not found, installing them now...
Preparing NPM for JXcore (v0.3.1.0) for the first run
Make sure the user account has a write permission to it's home folder. >> No se puede crear el directorio o archivo.

 Consider using a custom path from jx.config file's 'npmjxPath' property.

Do you have jx.config or that for win10 to make it work? pls send zip or something lol.

with the same bat the previous version worked perfectly

**Comment by JaraLowell** [comment]
Screenshot says, no write permissions to install node modules. So that might be why it trows out errors as it also tries to make a log folder and log files on first run.
