### ISSUE TITLE
help wanted: how did you put the server files into an exe file?

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#56]

**Comment by JaraLowell** [comment]
Visit JXCore, and see the compile to exe documentation there.

**Comment by ghost** [comment]
ok

**Comment by JaraLowell** [comment]
When you have JXCore installed
`jx package index.js OgarServ -native`
in the folder you have index inside, do not forget jx install.... for the node modules etc

**Comment by Agarian** [comment]
i cant do this now im in school xP

**Comment by ghost** [comment]
ok but how did you get the EXE to have a cell icon?

**Comment by JaraLowell** [comment]
by changing the icon of jx.exe :smile: though can obviously also change it of the exe... but i am lazy. Google, `ResourceHacker`

**Comment by Agarian** [comment]
how do i change it??
