### ISSUE TITLE
why this error?

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#58]
and wtf is underscore?
![why](https://cloud.githubusercontent.com/assets/15255724/12769974/5e63ba6a-c9ea-11e5-9eb5-c590441e5333.png)

**Comment by ghost** [comment]
actually i fixed it.

**Comment by JaraLowell** [comment]
i did write we drop request :P and use url/underscore now. as request has like.. 30k of packages...

**Comment by ghost** [comment]
i told you before i would be hellcat ;-;
