### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by sheepman12321** [JaraLowell/OgarServ#59]
How Do I Join It???

**Comment by makandz** [comment]
?

**Comment by sheepman12321** [comment]
how do i join the server!

**Comment by makandz** [comment]
Windows: Download it and open up the start.bat in the server and go to http://agar.io/?ip=127.0.0.1:4411.

Linux: Open Terminal and go to the folder of the src. Then type in sh runserver.sh, and do the same thing to join as Windows.

**Comment by Andrews54757** [comment]
BTW do you know any other client that supports chat? I know it is not the scope of this project but to tell the truth, THERE ARE NO OTHER FORUMS THAT ANSWER IT THAT HAVE THE CLIENT. All the other clients are gone.

**Comment by JaraLowell** [comment]
There are other forums... one of the most famous, ragezone so no here we dont know about any client supporting it. Though technikly you only need an java script to like fork in to client and puts a new div.. but yah.. ragezone :smile:
