### ISSUE TITLE
Unable to move.

### ISSUE THREAD

**Issue by Qasimmodo** [JaraLowell/OgarServ#6]
I'm unable to move, all the bots seem to be able to move.

**Comment by JaraLowell** [comment]
Means your client not sends the right 'move' package or your client is not compatible with the server you got. Is why there be ogar, and agar; Ogar is for older clients, while Agar is for current agar.io based clients

**Comment by Qasimmodo** [comment]
I tried both of them, with Ogar, I get stuck at the top left and my cell becomes "scrunched up".

**Comment by JaraLowell** [comment]
Apparently somewhere in one of the edits, the two files where somewhat damaged. Fixed now! Happy playing
