### ISSUE TITLE
Why this error on centos 7?

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#60]
Im getting this... http://prntscr.com/9yd7u7 anyone can help pls

**Comment by skyleter** [comment]
Easy and quick fix. 

changed         `var splitSpeed = this.config.playerSplitSpeed * Math.max(Math.log10(newMass) - 2.2, 1); //for smaller cells use splitspeed 150, for bigger cells add some speed
`

to 

`var splitSpeed = cell.getSpeed() * 6;`

(1.6.1 code)

Good luck everyone having this issue atm

**Comment by skyleter** [comment]
Please fix it, the `var splitSpeed = cell.getSpeed() * 6;` its not enough.

**Comment by JaraLowell** [comment]
Bit strange your server hangs on `log10` as this is a current java way of calculating a float value. But if the issue is that change it to Math.max(Math.log(newMass, 10) - 2.2, 1) and see if the older way works :smile:

**Comment by skyleter** [comment]
Worked so bad... Not better than cell.getSpeed() \* 6;

**Comment by skyleter** [comment]
Lol i had to delete the folder,acces via SFTP, download source code, transfer, reinstall jx modules, many things :s but fixed :smile:

**Comment by skyleter** [comment]
ps join => www.agary.info
