### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#61]
....
a-Can please make a cmd to force all mothercells to spawn the food faster or instantly? :smile: [only for experimental]

b..--- How i can show up to 20 top players in leaderboard? thanks

**Comment by skyleter** [comment]
P.S sometimes mothercell are losing ALL mass and not spawning "food" -_-

**Comment by JaraLowell** [comment]
Max food, in config ini, leader board length in config ini  both can be changed. even in experimental when you reach max food you can spawn food, or you have a huge lag issue with one mother cell aka virus with like a million of food around it.

**Comment by makandz** [comment]
To remove the mothercell from following the config.MaxFood thing. Check the gamemodes/Experimental.js and find the if statement in spawning food to check for the maxfood. I have this done on my own server, if you want more info just ask me :D

**Comment by skyleter** [comment]
thank you! How and where i can contact you for more help? =P

**Comment by makandz** [comment]
You don't need to. I am adding this feature to OgarServ where you can edit it in the config xD I have it done, just doing a couple more changes and I will be releasing it as a pull request sometime tonight.

**Comment by skyleter** [comment]
what feature?

**Comment by skyleter** [comment]
Do you know why ogarserv is not updating my mysql table but it is connected yet and with players online?

**Comment by makandz** [comment]
This was solved in my commit a while ago.

@JaraLowell Close xD
