### ISSUE TITLE
global.gc() code position

### ISSUE THREAD

**Issue by Ciao121** [JaraLowell/OgarServ#62]
I saw you added global.gc() to use --expose-gc. I'm not really inside programming so I try to ask.
You put global.gc() inside "GameServer.prototype.MasterPing"; t'hats because this code section is causing a leak or just because is a code executed frequently?
Thank you.

**Comment by JaraLowell** [comment]
global.gc() is the garbage collector for node, or more the ws side. and any other unused arrays that are older then x time. Java only executes it when a certain memory threshold is reached. By forcing it to run a few more times. in Masterping case on connect and every 30 min we force it to clean up trough out the whole server alive phase. It will still grow, memory that is, there noting it seems we can do about that. However after some tests, and with gc on; after 12 hours, and 900+ connections memory cam only as high as 150Kb while we seen older cases where after 12 hours we where over a 300Kb and even some server nearing 900Kb every little bit helps. We do know moment we get close to 300K the server becomes some what lagy. So perhaps a auto reset be more usable to happen when memory is over x value then when x time has gone by. But anyways, that is why it is there :smile:
