### ISSUE TITLE
Request is not defined

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#63]
http://prntscr.com/9z0xht ... with fb login and => server stops

**Comment by JaraLowell** [comment]
yah i need revise the fbapi as we no longer use request; for now just make fbapi in game server empty till i fixed it to work with our current request way D:

**Comment by skyleter** [comment]
so i need to delete all lines of the file?

**Comment by skyleter** [comment]
accidentally closed xd

**Comment by JaraLowell** [comment]
just do... 
GameServer.prototype.fbapi = function (token, ip) {
};
so it wont cause an issue for now :smile:

**Comment by makandz** [comment]
Whenever I got the request error, I just removed the line of request in the Gameserver.js and the server worked fine. I think this was fixed in a newer version of OgarServ no?
