### ISSUE TITLE
new split issue(resolved)

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#64]
**you recently changed:**

```
    var splitSpeed = this.config.playerSplitSpeed * Math.max(Math.log10(newMass) - 2.2, 1);
```

**to:**

```
    var splitSpeed = this.config.playerSplitSpeed * Math.max(Math.log(newMass, 10) - 2.2, 1);
```

**the cell now splits across the whole map.**

**Comment by JaraLowell** [comment]
issue is... log10, is not supported by CentOS and apparently neither under windows >.> gues ,10 no works either ... cry

**Comment by ghost** [comment]
i use win7 it works fine for me
idk what CentOS is.

**Comment by ghost** [comment]
you could completely remove  \* Math.max(Math.log(newMass, 10) - 2.2, 1);
it still works but splitting is slower

**Comment by JaraLowell** [comment]
should be okay now... math.log10(x) is same as math.log(x)/2.3 why i tryed use ,10 is beyond me,,..

**Comment by ghost** [comment]
well idfk about the logs

**Comment by ghost** [comment]
as long as its fixed then thats good.

**Comment by JaraLowell** [comment]
this git clone is active now on ogar.mivabe.nl :stuck_out_tongue: lets test  and see for a few hours.. days if we good to go :D still would love to add the pretty Halloween mod i seen at agariohub as a mode for our lil community :blush:

**Comment by makandz** [comment]
Yeah it's fixed xD

**Comment by retslac** [comment]
> you could completely remove \* Math.max(Math.log(newMass, 10) - 2.2, 1);
>  it still works but splitting is slower

Agarian is right.  Well partly.  Result is just the same for smaller cells.  Only reason i added the log-part was for the bigger cells.  Especially for the really big cells like 100K this makes a big difference.  Just my opinion, but i find splitting looks better with the log for the bigger cells.

@JaraLowell Leuk projectje heb je hier :)  I see you also fixed the 'shaky' cells.  Do you maybe have an idea of how we can remove the shaky part, but still keep the big cells pushing harder against smaller cells?  Sorry for going a bit off topic here.

**Comment by ghost** [comment]
i was unsure about why that continued to happen. i tried changing it a little bit but i was unsuccessful.  some of the code was derived from Luka967. also i made the PR for the shaky cells lol

**Comment by ghost** [comment]
https://github.com/JaraLowell/OgarServ/pull/55

**Comment by retslac** [comment]
@Agarian Yep, i know it comes from Luka967.  Just wandering if maybe Jara has some other insight or ideas about the matter.  Would still like to solve this.

**Comment by ghost** [comment]
you should fork ogar and add your server code. i'm interested in what it would have in store (feature and physics wise)

**Comment by retslac** [comment]
Fork, maybe later.  I'll think about it.  Not sure you're gonna get something out of it.  I think you've seen just about all physics code of me.  Features is still a work in progress.  Currently mainly working on the serverbots AI and helping OgarUnite a bit with his project.
