### ISSUE TITLE
Custom leaderboard text before "leaderboard"?

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#66]
Supposing my leaderboard is 15 length. How i can do something like this:

+--------------------+
|   Leaderboard   |
|   1. Text             |
|   2. Text 2          |
|   3. text 3           |
|  4. text 4            |
|  5. -------------    |
| 6 to 15 = users  |
+--------------------+

I mean, leaderboard with max 15 length required to display 4 strings and at the 5 line a ------ [separate]
and at line 6 to line 15, display the leaderboard. Like this
1. Players: number
2.  JOIN NOW
3. TO
4. AGARY.INFO
5. ---------------
6. user1
7. leader2
8. more users...

and so on..
It is possible?

**Comment by Andrews54757** [comment]
Im going to create this feature in my fork soon

**Comment by skyleter** [comment]
thank you

**Comment by skyleter** [comment]
whats your fork

**Comment by ghost** [comment]
https://github.com/AJS-development/Ogar-unlimited

**Comment by skyleter** [comment]
it is already on it?

**Comment by JaraLowell** [comment]
Bin playing with that once a while to, it apparently easy to like have score, or only text; but mixing them together is a whole other story. Mainly because original ogarproject loves to like push a whole array to a function rather then send only what is needed, so this makes it a whole lot harder to clean it up as you have then to clean it up in a few files and functions. i'l commit the no players function displaying welcome and time on leaderboard when there be no players to show. Just for fun and giggles.

**Comment by ghost** [comment]
@mogokcp not yet stay tuned

**Comment by skyleter** [comment]
PS Jara, my server is connected to mysql on vps and it just creates the table but it does not add any row. Why'
\ @Agarian  ok

**Comment by JaraLowell** [comment]
Make sure it has the rights to do so, make sure MySQL connection not times out. And it only logs players with a score like higher then .. 100? if i remeber...

**Comment by skyleter** [comment]
root AND i configured mysql.ini with root mysql user. it does not say timed out and on my server i got +20k and nothing

**Comment by JaraLowell** [comment]
No error either?

**Comment by skyleter** [comment]
http://prntscr.com/9zkaqj

**Comment by JaraLowell** [comment]
i mean in OgarServ's console/log

**Comment by skyleter** [comment]
nope

**Comment by JaraLowell** [comment]
Arg, apparently when making updating free roam mode, we sorta deleted the SQL stuff... let me work on that tonight.. yep yep... i will commit as soon as i have it back working XD

**Comment by skyleter** [comment]
ok :+1:  thx

**Comment by JaraLowell** [comment]
Try the git version now :smile:

**Comment by ghost** [comment]
git?

**Comment by skyleter** [comment]
Yes, https://github.com/JaraLowell/OgarServ [not in releases] Only playertracker was edited

**Comment by JaraLowell** [comment]
The version i just commited, git clone ? (on linux) or a git client for windows, or get the zip file https://github.com/JaraLowell/OgarServ/archive/master.zip

**Comment by skyleter** [comment]
thank you! now its working like a charm! but please add the feature of the leaderboard!!
1. players: + " playernumbers 
   2----TEXT
   3-. TEXT
   4---. TEXT
   5--. ------
   6 TO 15 : USERS

**Comment by Andrews54757** [comment]
@mogokcp  I have created a plugin that adds stuff to the **end** of the leaderboard though here https://github.com/AJS-development/OgarUL-Plugin-Library. Its for ogar unlimited though

**Comment by ghost** [comment]
Make 1 for ogar unlimited please? Lol

**Comment by Andrews54757** [comment]
???

**Comment by Andrews54757** [comment]
do you mean ogarserv?

**Comment by ghost** [comment]
fk me i ddnt read it correctly... nvm about it
