### ISSUE TITLE
Premium skins?

### ISSUE THREAD

**Issue by skyleter** [JaraLowell/OgarServ#69]
Please update ogarserv with premium skins feature just like http://agar.io/?ip=parisgamma.iomods.com:1501 
example name:

<kraken> Skyleter
my name will be skyleter with the kraken skin ON THE OFFICIAL AGARIO CLIENT

plss :smile:

**Comment by JaraLowell** [comment]
That is client side, not server.

**Comment by Andrews54757** [comment]
no it isnt, what about parisgamma.iomods?

**Comment by skyleter** [comment]
^  yes.

**Comment by Andrews54757** [comment]
[here](http://agar.io/?ip=parisgamma.iomods.com:1501)
To use a skin, put your skin name enclosed in a <> and you name afterwards. ex `<spy> lol`

**Comment by skyleter** [comment]
ups
example name was
`<kraken> Skyleter` ***

**Comment by ItzLevvie** [comment]
@JaraLowell It can be done both, client and server side.

**Comment by JaraLowell** [comment]
Personally do now know what the server has to do to activate a premium skin, so any insight on that would be help full.

**Comment by Andrews54757** [comment]
I found out the protocal to do it but I dont know how to use it

**Comment by JaraLowell** [comment]
Do share :smile:

**Comment by Andrews54757** [comment]
Its all here http://agar.gcommer.com/index.php?title=Protocol and I highly doubt @ItzLevvie has the code.

**Comment by JaraLowell** [comment]
Well i have one part of it down, but it not works for me, do you need to have premium to actually have it working?

**Comment by ItzLevvie** [comment]
@JaraLowell If you didn't know Premium skins and Veteran skins can be found at http://agar.io/skins/premium/<skinName>.png (e.g. [http://agar.io/skins/premium/Venus.png])

**Comment by Andrews54757** [comment]
Can you tell us what you did

**Comment by JaraLowell** [comment]
it actually not the skin it sends... even though i apparently did all corect, and send the correct info (least i think) the client on my end still not picks it up. See `packet/UpdateNodes.js` for what it is.

**Comment by skyleter** [comment]
Not working! see this. http://prntscr.com/a001j8 -> show my name as sk but it does not  update anything. its more , it bugs food and cell...http://prntscr.com/a001qn cand write anything in console also due to this. Need to restart vps

**Comment by skyleter** [comment]
you set agar.io/skins/premium/....png as locationn? ...

**Comment by JaraLowell** [comment]
dont get a git when i am working on it :P lo; though for tonighti gone call it. four am and still not have it working. i do think that ' current'  git is working but let me know if not; premium skin now gets set. but agar.io client still returns nada. So am a bit clueless now really

**Comment by skyleter** [comment]
thank you for  your time

-im sure ill se natsuthegreat there soon-
ps f... u  natsu :-)

**Comment by skyleter** [comment]
tell me if you make it work pls
