### ISSUE TITLE
Feed bug

### ISSUE THREAD

**Issue by J0113** [JaraLowell/OgarServ#70]
If I eat a virus and feed some mass, the screen will bug and you can't play any longer, on every client I try, is this a client thing or has everyone this bug? Btw in the config I have changed that you can have max 32 cells (may is it something with that?)

Thanks!

**Comment by ghost** [comment]
same issue but it happens with alot of other things
even eating mothercells with **lots** of food around it

**Comment by makandz** [comment]
I had this issue before too. But it would always freeze when I would touch a virus or even at random times. I fixed it by getting a better server, for some reason it happens with servers that have a small ping.

**Comment by J0113** [comment]
@MastaCoder Wait, how do you fixed it? By getting a better server, what do you mean with that?

**Comment by makandz** [comment]
@jollesnaas Like a more powerful server with better latency. I got the issue before when I had a 100 ping server from my place, updated to 30 ping and only ever had one person complain about it.

**Comment by makandz** [comment]
Also Jara's server doesn't have the issue at all ;-;

**Comment by JaraLowell** [comment]
my OgarServ run on a Intell SR2500 dual CPU 8GB ram
Yes dual CPU as in 2x Intel® Xeon® E5410 @ 2.33GHz so total 8 cores. on a gigabit network
![My Server](http://www.speedtest.net/result/5069847482.png)
![My Server](http://www.spectrumservers.com/ssproducts/pc/catalog/SR2500ALLXRNA-det.jpg)

**Comment by ghost** [comment]
jara u lucky to have that computer. i have 2 cores and 4gb ram ;-;

**Comment by ItzLevvie** [comment]
I've a 1000+ Mbps network, 256 GB DDR5 RAM and 1490 GB SSD.

**Comment by ItzLevvie** [comment]
I've a 1000+ Mbps network, 256 GB DDR4 RAM and 1490 GB SSD.

**Comment by J0113** [comment]
I've my server on a 1 gig ram and a 2 core vps running... :disappointed_relieved:

**Comment by J0113** [comment]
@JaraLowell Can it be fixed? Or do I need a better VPS/Client?

**Comment by JaraLowell** [comment]
A VPS, is never a smart idea to be used to host a game server. As it is a virtual machine in an computer. What means you share the resources with other virtual machines on the same host. As any game hosting person would tell you. You not go and run Counter strike on a VPS for 100 people. Nor an Ragnarok server or Mine Craft as you will always have lag and not the full CPU to use, nor the full bandwidth.

**Comment by J0113** [comment]
@JaraLowell I'm not sure of this is a VPS or something else, my host is [cloudatcost](http://cloudatcost.com). I can connect via the website or with windows remote desktop and use it as a normal computer. (and host my ogarserv server!) I have the cloud 2 package.

**Comment by JaraLowell** [comment]
Most online services where you rent and shell, are VPS; they most time host up to 8 virtual machines on one dedicated server or even more.

**Comment by J0113** [comment]
@JaraLowell You think that that is the reason? (That feed bug) And by cloudatcost I have a server forever.

**Comment by skyleter** [comment]
@ItzLevvie $$$

**Comment by makandz** [comment]
Is this solved?
