### ISSUE TITLE
forever jxcore?

### ISSUE THREAD

**Issue by mafiakb** [JaraLowell/OgarServ#71]
how add forever run server with forever?

**Comment by makandz** [comment]
?

**Comment by skyleter** [comment]
what?

**Comment by Andrews54757** [comment]
I think he means a server that can run forever. To make your server run continuousely, you need to be on a windows computer

**Comment by JaraLowell** [comment]
Forever is basically used by them 16bit Minecraft servers...https://github.com/foreverjs/forever it keeps an scripe node or other wise running even if it crashes. Unfortunately in our case, we need close the whole thing out and restart to actually clear memory and is what most Linux slash windows people do. Mu SH file does just that and if yuo want have it in background.. "./runserver.sh > console.log &" and we in the background and console is logged to.. console.log.
