### ISSUE TITLE
Can't connect??

### ISSUE THREAD

**Issue by J0113** [JaraLowell/OgarServ#74]
Hey, when I connect to a client the server will stop immediately so you can't play. Is this a bug or... Some help please, I've my client protocol or something to version 1 and 0 but it won't work. Anyone else the same problem. Btw, I use the ogar.mivabe.nl client and the ogar.be client. If that info is needed.

**Comment by J0113** [comment]
I don't know what it was but I fixed automatically! Now I have my server running on [this](http://playagar.hol.es/) website! Thanks Jara for this awesome project!

**Comment by JaraLowell** [comment]
Glad it fixed, maybe an windows auto update that caused it so? eheh :D
