### ISSUE TITLE
.EXE Problem

### ISSUE THREAD

**Issue by olivierek6** [JaraLowell/OgarServ#75]
When i turn the program on. I wait 9 seconds while playing and that program closes. i need help

**Comment by J0113** [comment]
I've the same problem but by me it exit's when I connect to the server: #74

**Comment by Andrews54757** [comment]
I dont know why this happens

**Comment by JaraLowell** [comment]
Seems chat can crash the windows executable for some odd reason am investigating this before releasing 1.6.4

**Comment by olivierek6** [comment]
Fixed and i was logged to facebook and it shutted down, i'm not connected and i can play :)
