### ISSUE TITLE
I have some errors with mass(not defined)

### ISSUE THREAD

**Issue by morenja** [JaraLowell/OgarServ#83]
http://prntscr.com/a39mzz
I have this error if i give mass or eat other cell.

**Comment by makandz** [comment]
Uh oh. Let me check it out.

**Comment by makandz** [comment]
Found it. I made a pull request, let's wait for Jara to accept. 

You can download my version if you need it ASAP: https://github.com/MastaCoder/OgarServ

**Comment by JaraLowell** [comment]
Pull request accepted

**Comment by makandz** [comment]
@JaraLowell Close request? xD
