### ISSUE TITLE
Zoom Problem

### ISSUE THREAD

**Issue by casperkral12** [JaraLowell/OgarServ#85]
500K MASS Zoom Problem :(
![adsiz](https://cloud.githubusercontent.com/assets/17240216/13037027/86ec4eea-d37f-11e5-86cc-3e2ed88e52b6.png)

How can we solve
it does not look around

**Comment by makandz** [comment]
What is your serverVersion in gameserver.ini

**Comment by JaraLowell** [comment]
lol

**Comment by casperkral12** [comment]
500k after the ball does not fit the screen 

server version 1

**Comment by JaraLowell** [comment]
500K is seriously big ! like not designed to be in this game big >.>

**Comment by makandz** [comment]
You're also using a client that doesn't support version 1. Change the serverVersion to 0.

**Comment by casperkral12** [comment]
http://agario.biz/

zoom feature set here how can I do the same ?

**Comment by fakeusername1029391323** [comment]
I have the exact same issue! Im just this giant bloop of death in the middle of the map and cant do anything is there a fix for this or something? I want the player to start small and get bigger etc..
