### ISSUE TITLE
Maybe a video for beginners?

### ISSUE THREAD

**Issue by AlexandriteErikParacelsus** [JaraLowell/OgarServ#90]
It would help a lot of people.

**Comment by makandz** [comment]
This is very similar to Ogar, simply run the start.bat and connect to the server like any other Ogar server.

**Comment by JaraLowell** [comment]
Why would a video be needed? Mean simply run the program and poof connect using http://agar.io/?ip= your ip:port... and play. I trully not see how a video be needed there other then seeing somebody press start.bat. Mean it is obviously you need node or jxcore installed if you use the scripts.

**Comment by AlexandriteErikParacelsus** [comment]
Doesn't work for me when i use start.bat, when i use it my start.bat will start to npm install something and turn off.

**Comment by olivierek6** [comment]
1. make file .bat
2. type in @echo off node index.js pause
3. run the bat file
4. have fun with your server

**Comment by makandz** [comment]
Make sure for step two echo off and node index.js and pause are on separate lines.

**Comment by AlexandriteErikParacelsus** [comment]
Thank you for your help.

**Comment by makandz** [comment]
@JaraLowell Close req :+1:
