### ISSUE TITLE
Application Shutdown Problem

### ISSUE THREAD

**Issue by CAvcii** [JaraLowell/OgarServ#93]
Hello,
I'm using the 1.6.2 version. I have CentOS operating system. I am running index.js file with the JX Core Screen mode. A self-closing time. Why could it be?

However, I tried to install the Windows Server 2012 operating system. But minutes after server work program he would cover himself in the same way. What is the problem?

**Comment by JaraLowell** [comment]
Will do some tests this week and if everything works will make release 1.6.3 and hope that all those issues be gone.
