### ISSUE TITLE
Sticky Cell

### ISSUE THREAD

**Issue by Ciao121** [JaraLowell/OgarServ#94]
Hi Jara,
I'm implementing Stiky Cells on my own Ogar modded version. I saw on mivabe those are not rounds while on mine they are rounds; is this a client feature or a I missing something?

Thank you!

**Comment by JaraLowell** [comment]
this.agitated = 1, makes them wobbly :stuck_out_tongue:

**Comment by Ciao121** [comment]
And this.agitated = 1 it's not used in official client, am I right?

**Comment by JaraLowell** [comment]
Officialy they say not, but when you look with an agar.io client, you see the sticky cell being wobbly as well. What would mean it is in the official client as well.

**Comment by Ciao121** [comment]
You're right. I also tried connectin to mivabe server using the official client andI see them wobbly. So I'm missing something :)
Thank you!

**Comment by JaraLowell** [comment]
Check you UpdateNodes.js, just because your tell a cell to be one, not means your server actually sends it. As many of the servers out there not send the agitated bit.

**Comment by Ciao121** [comment]
Yeah, I was missing something in UpdateNodes.js, Cell.js and Playertracker (some dependencies).
Thanks!!!
