### ISSUE TITLE
People die when giving much mass

### ISSUE THREAD

**Issue by joery1337** [JaraLowell/OgarServ#97]
If someone gives their mass to someone really fast, and it's around 5k mass. Their new mass is 0 mass and they go to the top left corner and they can't move anymore.

**Comment by JaraLowell** [comment]
I have indeed tested this bug and it indeed a bug, will look in to it asap

**Comment by makandz** [comment]
How big is your ejectMass loss? This really happens to me when I forget to raise the minimum mass they can eject at.

**Comment by JaraLowell** [comment]
Actually we made a boo boo and is fixed now :sweat_smile: Was the fast decay that caused an issue.

**Comment by makandz** [comment]
Oh lol xD

**Comment by joery1337** [comment]
Thank you for fixing :)!
