### ISSUE TITLE
ogarmivable website bugged?

### ISSUE THREAD

**Issue by ghost** [JaraLowell/OgarServ#98]
spectating doesnt work(goes top left), you cannot to any other direction than left, you cannot zoom, its very odd

**Comment by JaraLowell** [comment]
I had same issue, till i resized my Firefox window O.o it then all worked perfectly even when i switched back to the original size i started with....

**Comment by JaraLowell** [comment]
Duplicate from Issue #97
Cell with zero mass caused this issue in my case, a bot or two stuck in the corner with no mass.
