### ISSUE TITLE
Server closes when a Facebook logged user joins

### ISSUE THREAD

**Issue by WorldLanguages** [JaraLowell/OgarServ#99]
When there's a player logged in with Facebook, the server closes.

**Comment by JaraLowell** [comment]
Need a  bit more, like on what operating system are you running it, any possible error logs etc. Mean simplicity is, you might have not given any rights to the log folder while you enabled logging. (no write permisions)

**Comment by mundofinky** [comment]
Sorry, I'm new to Github and I'm a kid ... xD 

I'm running Windows 8.1, intel core i5, 4gb ram.

I'm trying to record the error, because when it shows the program closes ._.

**Comment by mundofinky** [comment]
![captura de pantalla 465](https://cloud.githubusercontent.com/assets/17484114/13340118/839c7428-dc0c-11e5-8313-e41d43f14a4d.png)

**Comment by WorldLanguages** [comment]
Wow, I logged out of Facebook and the server worked! xD

**Comment by JaraLowell** [comment]
Version 1.6.2, try the current new version ? :smile:

**Comment by olivierek6** [comment]
I think the bug problem was for facebook

**Comment by JaraLowell** [comment]
Facebook Api was removed in commit d24ab17
